# Generated by Django 5.1.7 on 2025-03-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type_of_financial_entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        verbose_name="Codice del tipo di entità finanziaria",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione del tipo di entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type of Financial Entity",
                "verbose_name_plural": "Types of Financial Entities",
                "db_table": "Type_of_financial_entity",
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyVendor_B1_01_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        help_text="Identificare l'entità finanziaria che mantiene e aggiorna il registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        max_length=20,
                        unique=True,
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Denominazione legale dell'entità finanziaria che mantiene e aggiorna il registro delle informazioni.",
                        max_length=255,
                        verbose_name="Nome dell'entità finanziaria",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                        max_length=2,
                        verbose_name="Paese dell'entità finanziaria",
                    ),
                ),
                (
                    "competent_authority",
                    models.CharField(
                        blank=True,
                        help_text="Identificare l'autorità competente di cui all'articolo 46 del regolamento (UE) 2022/2554, a disposizione della quale è messo il registro delle informazioni.",
                        max_length=255,
                        null=True,
                        verbose_name="Autorità competente",
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        blank=True,
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di messa a disposizione.",
                        null=True,
                        verbose_name="Data della messa a disposizione",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="REGDORA.type_of_financial_entity",
                        verbose_name="Tipo di entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor (B1_01.01)",
                "verbose_name_plural": "Third-Party Vendors (B1_01.01)",
                "db_table": "ThirdPartyVendor-B1_01.01",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntity_B1_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        help_text="Identificare l'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        max_length=20,
                        unique=True,
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Denominazione legale dell'entità finanziaria segnalata nel registro delle informazioni.",
                        max_length=255,
                        verbose_name="Nome dell'entità finanziaria",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità finanziaria segnalata nel registro delle informazioni.",
                        max_length=2,
                        verbose_name="Paese dell'entità finanziaria",
                    ),
                ),
                (
                    "hierarchy",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "l'entità finanziaria è l'impresa madre capogruppo nel consolidamento",
                            ),
                            (
                                "2",
                                "l'entità finanziaria è l'impresa madre di una parte subconsolidata nel consolidamento",
                            ),
                            (
                                "3",
                                "l'entità finanziaria è un'impresa figlia nel consolidamento e non è un'impresa madre di una parte subconsolidata",
                            ),
                            ("4", "l'entità finanziaria non fa parte di un gruppo"),
                            (
                                "5",
                                "l'entità finanziaria è un fornitore di servizi al quale l'entità finanziaria (o il fornitore terzo di servizi che agisce per suo conto) esternalizza tutte le sue attività operative",
                            ),
                        ],
                        help_text="Determinare la gerarchia dell'entità finanziaria nel consolidamento utilizzando una delle opzioni nell'elenco chiuso.",
                        max_length=1,
                        verbose_name="Gerarchia dell'entità finanziaria all'interno del gruppo (se del caso)",
                    ),
                ),
                (
                    "last_update_date",
                    models.DateField(
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data dell'ultimo aggiornamento effettuato o dell'ultima modifica apportata nel registro delle informazioni in relazione all'entità finanziaria.",
                        verbose_name="Data dell'ultimo aggiornamento",
                    ),
                ),
                (
                    "integration_date",
                    models.DateField(
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di integrazione dell'entità finanziaria nel registro delle informazioni.",
                        verbose_name="Data dell'integrazione nel registro delle informazioni",
                    ),
                ),
                (
                    "deletion_date",
                    models.DateField(
                        default="9999-12-31",
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di cancellazione dell'entità finanziaria dal registro delle informazioni. Se l'entità finanziaria non è stata cancellata, inserire «9999-12-31».",
                        verbose_name="Data della cancellazione dal registro delle informazioni",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta utilizzata per la preparazione del bilancio d'esercizio dell'entità finanziaria.",
                        max_length=3,
                        null=True,
                        verbose_name="Valuta",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valore monetario delle attività totali dell'entità finanziaria come segnalato nel bilancio dell'entità finanziaria dell'esercizio precedente la data dell'ultimo aggiornamento del registro delle informazioni.",
                        max_digits=20,
                        null=True,
                        verbose_name="Valore delle attività totali dell'entità finanziaria",
                    ),
                ),
                (
                    "parent_lei",
                    models.ForeignKey(
                        blank=True,
                        help_text="Identificare l'impresa madre diretta dell'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_entities",
                        to="REGDORA.thirdpartyvendor_b1_01_01",
                        verbose_name="LEI dell'impresa madre diretta dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="REGDORA.type_of_financial_entity",
                        verbose_name="Tipo di entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity (B1_02)",
                "verbose_name_plural": "Financial Entities (B1_02)",
                "db_table": "FinancialEntity-B1_02",
            },
        ),
    ]
