# Generated by Django 5.1.7 on 2025-03-29 06:37

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractAgreement_B2_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.CharField(
                        help_text="Identificare l'accordo contrattuale tra l'entità finanziaria e il fornitore terzo diretto di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("1", "accordo autonomo"),
                            ("2", "accordo contrattuale generale/master"),
                            ("3", "accordo successivo o associato"),
                        ],
                        help_text="Identificare il tipo di accordo contrattuale.",
                        max_length=1,
                        verbose_name="Tipo di accordo contrattuale",
                    ),
                ),
                (
                    "general_contract_reference",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale generale.",
                        max_length=255,
                        null=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale generale",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta utilizzata.",
                        max_length=3,
                        verbose_name="Valuta dell'importo segnalato",
                    ),
                ),
                (
                    "estimated_annual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Spese o costi stimati annuali dell'accordo contrattuale per l'anno passato.",
                        max_digits=20,
                        verbose_name="Spese o costi stimati annuali",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Agreement (B2_01)",
                "verbose_name_plural": "Contract Agreements (B2_01)",
                "db_table": "ContractAgreement-B2_01",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISO 4217 Code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Currency Name")),
                ("symbol", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "numeric_code",
                    models.PositiveSmallIntegerField(verbose_name="Numeric Code"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyVendor_B1_01_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        help_text="Identificare l'entità finanziaria che mantiene e aggiorna il registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        max_length=20,
                        unique=True,
                        verbose_name="B_01.01.0010\nLEI dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Denominazione legale dell'entità finanziaria che mantiene e aggiorna il registro delle informazioni.",
                        max_length=255,
                        verbose_name="B_01.01.0020\nNome dell'entità finanziaria",
                    ),
                ),
                (
                    "country_code",
                    django_countries.fields.CountryField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                        max_length=2,
                        verbose_name="B_01.01.0030\nPaese dell'entità finanziaria",
                    ),
                ),
                (
                    "competent_authority",
                    models.CharField(
                        blank=True,
                        help_text="Identificare l'autorità competente di cui all'articolo 46 del regolamento (UE) 2022/2554, a disposizione della quale è messo il registro delle informazioni.",
                        max_length=255,
                        null=True,
                        verbose_name="B_01.01.0050\nAutorità competente",
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        blank=True,
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di messa a disposizione.",
                        null=True,
                        verbose_name="B_01.01.0060\nData della messa a disposizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor (B1_01.01)",
                "verbose_name_plural": "Third-Party Vendors (B1_01.01)",
                "db_table": "ThirdPartyVendor-B1_01.01",
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyVendor_B5_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "additional_vendor_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice aggiuntivo per identificare il fornitore terzo di servizi TIC, ove disponibile.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo aggiuntivo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "additional_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Denominazione legale del fornitore terzo di servizi TIC come iscritta nel registro delle imprese.",
                        max_length=255,
                        verbose_name="Denominazione legale del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        help_text="Nome del fornitore terzo di servizi TIC in alfabeto latino.",
                        max_length=255,
                        verbose_name="Nome del fornitore terzo di servizi TIC in alfabeto latino",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "persona giuridica, escluse le persone fisiche che agiscono a titolo professionale",
                            ),
                            ("2", "persona fisica che agisce a titolo professionale"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la tipologia di persona.",
                        max_length=1,
                        verbose_name="Fornitore terzo di servizi TIC - tipologia di persona",
                    ),
                ),
                (
                    "headquarters_country",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è ubicata la sede operativa a livello mondiale del fornitore terzo di servizi TIC.",
                        max_length=2,
                        verbose_name="Paese della sede centrale del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta utilizzata per esprimere l'importo in B_05.01.0100.",
                        max_length=3,
                        null=True,
                        verbose_name="Valuta dell'importo segnalato",
                    ),
                ),
                (
                    "estimated_annual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Spese o costi stimati annuali per l'utilizzo dei servizi TIC prestati dal fornitore terzo di servizi TIC.",
                        max_digits=20,
                        null=True,
                        verbose_name="Spese o costi stimati annuali totali del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "parent_company_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo dell'impresa madre capogruppo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "parent_company_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor (B5_01)",
                "verbose_name_plural": "Third-Party Vendors (B5_01)",
                "db_table": "ThirdPartyVendor-B5_01",
            },
        ),
        migrations.CreateModel(
            name="Type_of_financial_entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        verbose_name="Codice del tipo di entità finanziaria",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione del tipo di entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type of Financial Entity",
                "verbose_name_plural": "Types of Financial Entities",
                "db_table": "Type_of_financial_entity",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntity_B1_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        help_text="Identificare l'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        max_length=20,
                        unique=True,
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Denominazione legale dell'entità finanziaria segnalata nel registro delle informazioni.",
                        max_length=255,
                        verbose_name="Nome dell'entità finanziaria",
                    ),
                ),
                (
                    "country_code",
                    django_countries.fields.CountryField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                        max_length=2,
                        verbose_name="B_01.02.0030\nPaese dell'entità finanziaria",
                    ),
                ),
                (
                    "hierarchy",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "l'entità finanziaria è l'impresa madre capogruppo nel consolidamento",
                            ),
                            (
                                "2",
                                "l'entità finanziaria è l'impresa madre di una parte subconsolidata nel consolidamento",
                            ),
                            (
                                "3",
                                "l'entità finanziaria è un'impresa figlia nel consolidamento e non è un'impresa madre di una parte subconsolidata",
                            ),
                            ("4", "l'entità finanziaria non fa parte di un gruppo"),
                            (
                                "5",
                                "l'entità finanziaria è un fornitore di servizi al quale l'entità finanziaria (o il fornitore terzo di servizi che agisce per suo conto) esternalizza tutte le sue attività operative",
                            ),
                        ],
                        help_text="Determinare la gerarchia dell'entità finanziaria nel consolidamento utilizzando una delle opzioni nell'elenco chiuso.",
                        max_length=1,
                        verbose_name="Gerarchia dell'entità finanziaria all'interno del gruppo (se del caso)",
                    ),
                ),
                (
                    "last_update_date",
                    models.DateField(
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data dell'ultimo aggiornamento effettuato o dell'ultima modifica apportata nel registro delle informazioni in relazione all'entità finanziaria.",
                        verbose_name="Data dell'ultimo aggiornamento",
                    ),
                ),
                (
                    "integration_date",
                    models.DateField(
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di integrazione dell'entità finanziaria nel registro delle informazioni.",
                        verbose_name="Data dell'integrazione nel registro delle informazioni",
                    ),
                ),
                (
                    "deletion_date",
                    models.DateField(
                        default="9999-12-31",
                        help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di cancellazione dell'entità finanziaria dal registro delle informazioni. Se l'entità finanziaria non è stata cancellata, inserire «9999-12-31».",
                        verbose_name="Data della cancellazione dal registro delle informazioni",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valore monetario delle attività totali dell'entità finanziaria come segnalato nel bilancio dell'entità finanziaria dell'esercizio precedente la data dell'ultimo aggiornamento del registro delle informazioni.",
                        max_digits=20,
                        null=True,
                        verbose_name="Valore delle attività totali dell'entità finanziaria",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_entities",
                        to="REGDORA.currency",
                        verbose_name="B_01.02.0100\nValuta",
                    ),
                ),
                (
                    "parent_lei",
                    models.ForeignKey(
                        blank=True,
                        help_text="Identificare l'impresa madre diretta dell'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_entities",
                        to="REGDORA.thirdpartyvendor_b1_01_01",
                        verbose_name="LEI dell'impresa madre diretta dell'entità finanziaria",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="REGDORA.type_of_financial_entity",
                        verbose_name="Tipo di entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity (B1_02)",
                "verbose_name_plural": "Financial Entities (B1_02)",
                "db_table": "FinancialEntity-B1_02",
            },
        ),
        migrations.CreateModel(
            name="ContractSigningEntity_B3_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'impresa.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "signing_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'impresa che firma l'accordo contrattuale utilizzando il LEI o l'EUID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_signing_entities",
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità che firma l'accordo contrattuale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Signing Entity (B3_01)",
                "verbose_name_plural": "Contract Signing Entities (B3_01)",
                "db_table": "ContractSigningEntity-B3_01",
            },
        ),
        migrations.CreateModel(
            name="ContractAgreementDetails_B2_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "third_party_vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "vendor_code_type",
                    models.CharField(
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "function_identifier",
                    models.CharField(
                        help_text="Identificativo della funzione come definito dall'entità finanziaria.",
                        max_length=255,
                        verbose_name="Identificativo della funzione",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Indicare la data di entrata in vigore dell'accordo contrattuale.",
                        verbose_name="Data di inizio dell'accordo contrattuale",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Indicare la data di fine stabilita nell'accordo contrattuale.",
                        verbose_name="Data di fine dell'accordo contrattuale",
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "risoluzione per scadenza naturale"),
                            (
                                "2",
                                "risoluzione per giusta causa (violazione di leggi/regolamenti)",
                            ),
                            (
                                "3",
                                "risoluzione per giusta causa (impedimenti del fornitore)",
                            ),
                            (
                                "4",
                                "risoluzione per giusta causa (gestione e sicurezza dei dati)",
                            ),
                            ("5", "risoluzione su richiesta di un'autorità competente"),
                            ("6", "altro"),
                        ],
                        help_text="Indicare il motivo della risoluzione o della fine dell'accordo contrattuale.",
                        max_length=1,
                        null=True,
                        verbose_name="Motivo della risoluzione o della fine dell'accordo contrattuale",
                    ),
                ),
                (
                    "financial_entity_notice_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte dell'entità finanziaria.",
                        null=True,
                        verbose_name="Termine di preavviso per l'entità finanziaria",
                    ),
                ),
                (
                    "vendor_notice_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte del fornitore terzo.",
                        null=True,
                        verbose_name="Termine di preavviso per il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "applicable_law_country",
                    models.CharField(
                        help_text="Indicare il paese del diritto applicabile all'accordo contrattuale.",
                        max_length=2,
                        verbose_name="Paese del diritto applicabile all'accordo contrattuale",
                    ),
                ),
                (
                    "service_provision_country",
                    models.CharField(
                        help_text="Indicare il paese da cui i servizi TIC sono prestati.",
                        max_length=2,
                        verbose_name="Paese da cui si prestano i servizi TIC",
                    ),
                ),
                (
                    "data_retention",
                    models.CharField(
                        choices=[("1", "Sì"), ("2", "No")],
                        help_text="Il servizio TIC riguarda (o prevede) la conservazione dei dati?",
                        max_length=1,
                        verbose_name="Conservazione dei dati",
                    ),
                ),
                (
                    "data_at_rest_location",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il paese di ubicazione dei dati «at rest».",
                        max_length=2,
                        null=True,
                        verbose_name="Ubicazione dei dati «at rest» (conservazione)",
                    ),
                ),
                (
                    "data_management_location",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il paese di ubicazione della gestione dei dati.",
                        max_length=2,
                        null=True,
                        verbose_name="Ubicazione della gestione dei dati (trattamento)",
                    ),
                ),
                (
                    "data_sensitivity",
                    models.CharField(
                        blank=True,
                        choices=[("1", "basso"), ("2", "medio"), ("3", "alto")],
                        help_text="Identificare il livello di sensibilità dei dati conservati o trattati dal fornitore terzo di servizi TIC.",
                        max_length=1,
                        null=True,
                        verbose_name="Sensibilità dei dati conservati dal fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "dependency_level",
                    models.CharField(
                        choices=[
                            ("1", "dipendenza irrilevante"),
                            ("2", "dipendenza modesta"),
                            ("3", "dipendenza significativa"),
                            ("4", "dipendenza totale"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per il livello di dipendenza dal servizio TIC.",
                        max_length=1,
                        verbose_name="Livello di dipendenza dal servizio TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_agreements",
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Agreement Details (B2_02)",
                "verbose_name_plural": "Contract Agreement Details (B2_02)",
                "db_table": "ContractAgreementDetails-B2_02",
            },
        ),
        migrations.CreateModel(
            name="Branch_B1_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="Identificare una succursale di un'entità finanziaria situata al di fuori del paese d'origine utilizzando un codice univoco per ciascuna succursale.",
                        max_length=255,
                        unique=True,
                        verbose_name="Codice identificativo della succursale",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="Indicare il nome della succursale.",
                        max_length=255,
                        verbose_name="Nome della succursale",
                    ),
                ),
                (
                    "branch_country",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui la succursale è ubicata.",
                        max_length=2,
                        verbose_name="Paese della succursale",
                    ),
                ),
                (
                    "head_office_lei",
                    models.ForeignKey(
                        help_text="Identificare la sede centrale dell'entità finanziaria da cui dipende la succursale utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI della sede centrale dell'entità finanziaria da cui dipende la succursale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch (B1_03)",
                "verbose_name_plural": "Branches (B1_03)",
                "db_table": "Branch-B1_03",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntityServiceProvider_B3_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'entità per la prestazione del servizio o dei servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "service_provider_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità che fornisce servizi TIC utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria che fornisce servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity Service Provider (B3_03)",
                "verbose_name_plural": "Financial Entity Service Providers (B3_03)",
                "db_table": "FinancialEntityServiceProvider-B3_03",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntityServiceUsage_B4_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_nature",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "l'entità finanziaria che si avvale del servizio o dei servizi TIC è una succursale dell'entità finanziaria",
                            ),
                            (
                                "2",
                                "l'entità finanziaria che si avvale del servizio o dei servizi TIC non è una succursale",
                            ),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la natura dell'entità finanziaria.",
                        max_length=1,
                        verbose_name="Natura dell'entità finanziaria che si avvale del servizio o dei servizi TIC",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice identificativo della succursale segnalato in B_01.03.0010.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo della succursale",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale connesso all'entità finanziaria che si avvale dei servizi TIC prestati.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria che si avvale del servizio o dei servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity Service Usage (B4_01)",
                "verbose_name_plural": "Financial Entity Service Usages (B4_01)",
                "db_table": "FinancialEntityServiceUsage-B4_01",
            },
        ),
        migrations.CreateModel(
            name="FunctionIdentification_B6_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_id",
                    models.CharField(
                        help_text="Identificativo della funzione univoco.",
                        max_length=255,
                        unique=True,
                        verbose_name="Identificativo della funzione",
                    ),
                ),
                (
                    "authorized_activity",
                    models.CharField(
                        choices=[("1", "Attività A"), ("2", "Attività B")],
                        help_text="Una delle attività autorizzate di cui agli atti giuridici sottostanti.",
                        max_length=1,
                        verbose_name="Attività autorizzata",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Nome della funzione sulla base dell'organizzazione interna dell'entità finanziaria.",
                        max_length=255,
                        verbose_name="Nome della funzione",
                    ),
                ),
                (
                    "essentiality",
                    models.CharField(
                        choices=[
                            ("1", "sì"),
                            ("2", "no"),
                            ("3", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la valutazione dell'essenzialità o dell'importanza.",
                        max_length=1,
                        verbose_name="Valutazione dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "essentiality_reasons",
                    models.TextField(
                        blank=True,
                        help_text="Breve spiegazione dei motivi per cui la funzione è stata classificata come essenziale o importante.",
                        null=True,
                        verbose_name="Motivi dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "last_evaluation_date",
                    models.DateField(
                        help_text="Data dell'ultima valutazione dell'essenzialità o dell'importanza.",
                        verbose_name="Data dell'ultima valutazione dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "recovery_time_objective",
                    models.PositiveIntegerField(
                        help_text="Obiettivo di tempo di ripristino della funzione in numero di ore.",
                        verbose_name="Obiettivo di tempo di ripristino della funzione",
                    ),
                ),
                (
                    "recovery_point_objective",
                    models.PositiveIntegerField(
                        help_text="Obiettivo di punto di ripristino della funzione in numero di ore.",
                        verbose_name="Obiettivo di punto di ripristino della funzione",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("1", "basso"),
                            ("2", "medio"),
                            ("3", "alto"),
                            ("4", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione della funzione.",
                        max_length=1,
                        verbose_name="Impatto dell'interruzione della funzione",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità finanziaria utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Function Identification (B6_01)",
                "verbose_name_plural": "Function Identifications (B6_01)",
                "db_table": "FunctionIdentification-B6_01",
            },
        ),
        migrations.CreateModel(
            name="IntraGroupContractAgreement_B2_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.CharField(
                        help_text="Numero di riferimento dell'accordo contrattuale tra l'entità che si avvale del servizio o dei servizi TIC e il fornitore intragruppo di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "linked_contract_reference",
                    models.ForeignKey(
                        help_text="Numero di riferimento dell'accordo contrattuale riguardante l'accordo tra il fornitore intragruppo di servizi TIC e il suo fornitore terzo diretto di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intra_group_contracts",
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Accordo contrattuale collegato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intra-Group Contract Agreement (B2_03)",
                "verbose_name_plural": "Intra-Group Contract Agreements (B2_03)",
                "db_table": "IntraGroupContractAgreement-B2_03",
            },
        ),
        migrations.CreateModel(
            name="SupplyChain_B5_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Come segnalato in B_05.01.0020 per tale fornitore terzo di servizi TIC.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Posizione del fornitore terzo di servizi TIC nella catena di approvvigionamento.",
                        verbose_name="Posizione",
                    ),
                ),
                (
                    "recipient_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice identificativo del destinatario dei servizi TIC subappaltati.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo del destinatario dei servizi TIC subappaltati",
                    ),
                ),
                (
                    "recipient_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "vendor_code",
                    models.ForeignKey(
                        help_text="Come segnalato in B_05.01.0010 per tale fornitore terzo di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.thirdpartyvendor_b5_01",
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Chain (B5_02)",
                "verbose_name_plural": "Supply Chains (B5_02)",
                "db_table": "SupplyChain-B5_02",
            },
        ),
        migrations.CreateModel(
            name="ServiceEvaluation_B7_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Come segnalato in B_05.01.0020.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "substitutability",
                    models.CharField(
                        choices=[
                            ("1", "non sostituibile"),
                            ("2", "sostituibilità molto complessa"),
                            ("3", "media complessità in termini di sostituibilità"),
                            ("4", "facilmente sostituibile"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la sostituibilità del fornitore terzo di servizi TIC.",
                        max_length=1,
                        verbose_name="Sostituibilità del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "substitutability_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "mancanza di alternative reali"),
                            ("2", "difficoltà inerenti alla migrazione"),
                            ("3", "entrambi i motivi di cui ai punti 1 e 2"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per il motivo della non sostituibilità.",
                        max_length=1,
                        null=True,
                        verbose_name="Motivo per cui il fornitore terzo di servizi TIC è considerato non sostituibile o difficilmente sostituibile",
                    ),
                ),
                (
                    "last_audit_date",
                    models.DateField(
                        help_text="Data dell'ultimo audit effettuato sugli specifici servizi TIC prestati dal fornitore terzo di servizi TIC.",
                        verbose_name="Data dell'ultimo audit sul fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "exit_plan",
                    models.CharField(
                        choices=[("1", "sì"), ("2", "no")],
                        help_text="Utilizzare una delle opzioni indicate per l'esistenza di un piano di uscita.",
                        max_length=1,
                        verbose_name="Esistenza di un piano di uscita",
                    ),
                ),
                (
                    "reintegration_possibility",
                    models.CharField(
                        choices=[
                            ("1", "facile"),
                            ("2", "difficile"),
                            ("3", "molto complessa"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la possibilità di reintegrazione del servizio TIC.",
                        max_length=1,
                        verbose_name="Possibilità di reintegrazione del servizio TIC previsto dal contratto",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("1", "basso"),
                            ("2", "medio"),
                            ("3", "alto"),
                            ("4", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione dei servizi TIC.",
                        max_length=1,
                        verbose_name="Impatto dell'interruzione dei servizi TIC",
                    ),
                ),
                (
                    "alternative_vendor",
                    models.CharField(
                        choices=[
                            ("1", "sì"),
                            ("2", "no"),
                            ("7", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'individuazione di fornitori terzi alternativi di servizi TIC.",
                        max_length=1,
                        verbose_name="Sono stati individuati fornitori terzi alternativi di servizi TIC?",
                    ),
                ),
                (
                    "alternative_vendor_details",
                    models.TextField(
                        blank=True,
                        help_text="Informazioni supplementari sui fornitori terzi alternativi di servizi TIC.",
                        null=True,
                        verbose_name="Individuazione di fornitori terzi alternativi di servizi TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "vendor_code",
                    models.ForeignKey(
                        help_text="Come segnalato in B_05.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.thirdpartyvendor_b5_01",
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Evaluation (B7_01)",
                "verbose_name_plural": "Service Evaluations (B7_01)",
                "db_table": "ServiceEvaluation-B7_01",
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyVendorSigning_B3_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "third_party_vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "vendor_code_type",
                    models.CharField(
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dal fornitore terzo di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor Signing (B3_02)",
                "verbose_name_plural": "Third-Party Vendor Signings (B3_02)",
                "db_table": "ThirdPartyVendorSigning-B3_02",
            },
        ),
        migrations.AddField(
            model_name="thirdpartyvendor_b1_01_01",
            name="entity_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.type_of_financial_entity",
                verbose_name="B_01.01.0040\nTipo di entità finanziaria",
            ),
        ),
    ]
