# Generated by Django 5.1.7 on 2025-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch_B1_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="Identificare una succursale di un'entità finanziaria situata al di fuori del paese d'origine utilizzando un codice univoco per ciascuna succursale.",
                        max_length=255,
                        unique=True,
                        verbose_name="Codice identificativo della succursale",
                    ),
                ),
                (
                    "head_office_lei",
                    models.CharField(
                        help_text="Identificare la sede centrale dell'entità finanziaria da cui dipende la succursale utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                        max_length=20,
                        verbose_name="LEI della sede centrale dell'entità finanziaria da cui dipende la succursale",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="Indicare il nome della succursale.",
                        max_length=255,
                        verbose_name="Nome della succursale",
                    ),
                ),
                (
                    "branch_country",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui la succursale è ubicata.",
                        max_length=2,
                        verbose_name="Paese della succursale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch (B1_03)",
                "verbose_name_plural": "Branches (B1_03)",
                "db_table": "Branch-B1_03",
            },
        ),
    ]
