# Generated by Django 5.1.7 on 2025-03-29 07:26

from django.db import migrations



# REGDORA/migrations/0002_load_financial_entity_types.py
from django.db import migrations

# Initial data (preserves your current model structure)
FINANCIAL_ENTITY_TYPES = [
    {"code": "01", "description": "enti creditizi"},
    {"code": "02", "description": "istituti di pagamento, compresi gli istituti di pagamento esentati"},
    {"code": "03", "description": "prestatori di servizi di informazione sui conti"},
    {"code": "04", "description": "istituti di moneta elettronica, compresi gli istituti di moneta elettronica esentati"},
    {"code": "05", "description": "imprese di investimento"},
    {"code": "06", "description": "prestatori di servizi per le cripto-attività autorizzati"},
    {"code": "07", "description": "emittenti di token collegati ad attività autorizzati"},
    {"code": "08", "description": "depositari centrali di titoli"},
    {"code": "09", "description": "controparti centrali"},
    {"code": "10", "description": "sedi di negoziazione"},
    {"code": "11", "description": "repertori di dati sulle negoziazioni"},
    {"code": "12", "description": "gestori di fondi di investimento alternativi"},
    {"code": "13", "description": "società di gestione"},
    {"code": "14", "description": "fornitori di servizi di comunicazione dati"},
    {"code": "15", "description": "imprese di assicurazione e di riassicurazione"},
    {"code": "16", "description": "intermediari assicurativi, intermediari riassicurativi e intermediari assicurativi a titolo accessorio"},
    {"code": "17", "description": "enti pensionistici aziendali o professionali"},
    {"code": "18", "description": "agenzie di rating del credito"},
    {"code": "19", "description": "amministratori di indici di riferimento critici"},
    {"code": "20", "description": "fornitori di servizi di crowdfunding"},
    {"code": "21", "description": "repertori di dati sulle cartolarizzazioni"},
    {"code": "22", "description": "altra entità finanziaria"},
]

def add_initial_data(apps, schema_editor):
    Type_of_financial_entity = apps.get_model("REGDORA", "Type_of_financial_entity")
    for item in FINANCIAL_ENTITY_TYPES:
        Type_of_financial_entity.objects.create(**item)

def remove_initial_data(apps, schema_editor):
    Type_of_financial_entity = apps.get_model("REGDORA", "Type_of_financial_entity")
    for item in FINANCIAL_ENTITY_TYPES:
        Type_of_financial_entity.objects.filter(code=item["code"]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("REGDORA", "0001_initial"),  # Depends on your initial migration
    ]

    operations = [
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]