# Generated by Django 5.1.7 on 2025-03-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0002_branch_b1_03"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch_b1_03",
            name="head_office_lei",
            field=models.ForeignKey(
                help_text="Identificare la sede centrale dell'entità finanziaria da cui dipende la succursale utilizzando il LEI.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI della sede centrale dell'entità finanziaria da cui dipende la succursale",
            ),
        ),
    ]
