# Generated by Django 5.1.7 on 2025-03-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0003_alter_branch_b1_03_head_office_lei"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAgreement_B2_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.CharField(
                        help_text="Identificare l'accordo contrattuale tra l'entità finanziaria e il fornitore terzo diretto di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("1", "accordo autonomo"),
                            ("2", "accordo contrattuale generale/master"),
                            ("3", "accordo successivo o associato"),
                        ],
                        help_text="Identificare il tipo di accordo contrattuale.",
                        max_length=1,
                        verbose_name="Tipo di accordo contrattuale",
                    ),
                ),
                (
                    "general_contract_reference",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale generale.",
                        max_length=255,
                        null=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale generale",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta utilizzata.",
                        max_length=3,
                        verbose_name="Valuta dell'importo segnalato",
                    ),
                ),
                (
                    "estimated_annual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Spese o costi stimati annuali dell'accordo contrattuale per l'anno passato.",
                        max_digits=20,
                        verbose_name="Spese o costi stimati annuali",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Agreement (B2_01)",
                "verbose_name_plural": "Contract Agreements (B2_01)",
                "db_table": "ContractAgreement-B2_01",
            },
        ),
        migrations.CreateModel(
            name="ContractAgreementDetails_B2_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.CharField(
                        help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC.",
                        max_length=20,
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
                (
                    "third_party_vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "vendor_code_type",
                    models.CharField(
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "function_identifier",
                    models.CharField(
                        help_text="Identificativo della funzione come definito dall'entità finanziaria.",
                        max_length=255,
                        verbose_name="Identificativo della funzione",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Indicare la data di entrata in vigore dell'accordo contrattuale.",
                        verbose_name="Data di inizio dell'accordo contrattuale",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Indicare la data di fine stabilita nell'accordo contrattuale.",
                        verbose_name="Data di fine dell'accordo contrattuale",
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "risoluzione per scadenza naturale"),
                            (
                                "2",
                                "risoluzione per giusta causa (violazione di leggi/regolamenti)",
                            ),
                            (
                                "3",
                                "risoluzione per giusta causa (impedimenti del fornitore)",
                            ),
                            (
                                "4",
                                "risoluzione per giusta causa (gestione e sicurezza dei dati)",
                            ),
                            ("5", "risoluzione su richiesta di un'autorità competente"),
                            ("6", "altro"),
                        ],
                        help_text="Indicare il motivo della risoluzione o della fine dell'accordo contrattuale.",
                        max_length=1,
                        null=True,
                        verbose_name="Motivo della risoluzione o della fine dell'accordo contrattuale",
                    ),
                ),
                (
                    "financial_entity_notice_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte dell'entità finanziaria.",
                        null=True,
                        verbose_name="Termine di preavviso per l'entità finanziaria",
                    ),
                ),
                (
                    "vendor_notice_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte del fornitore terzo.",
                        null=True,
                        verbose_name="Termine di preavviso per il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "applicable_law_country",
                    models.CharField(
                        help_text="Indicare il paese del diritto applicabile all'accordo contrattuale.",
                        max_length=2,
                        verbose_name="Paese del diritto applicabile all'accordo contrattuale",
                    ),
                ),
                (
                    "service_provision_country",
                    models.CharField(
                        help_text="Indicare il paese da cui i servizi TIC sono prestati.",
                        max_length=2,
                        verbose_name="Paese da cui si prestano i servizi TIC",
                    ),
                ),
                (
                    "data_retention",
                    models.CharField(
                        choices=[("1", "Sì"), ("2", "No")],
                        help_text="Il servizio TIC riguarda (o prevede) la conservazione dei dati?",
                        max_length=1,
                        verbose_name="Conservazione dei dati",
                    ),
                ),
                (
                    "data_at_rest_location",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il paese di ubicazione dei dati «at rest».",
                        max_length=2,
                        null=True,
                        verbose_name="Ubicazione dei dati «at rest» (conservazione)",
                    ),
                ),
                (
                    "data_management_location",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il paese di ubicazione della gestione dei dati.",
                        max_length=2,
                        null=True,
                        verbose_name="Ubicazione della gestione dei dati (trattamento)",
                    ),
                ),
                (
                    "data_sensitivity",
                    models.CharField(
                        blank=True,
                        choices=[("1", "basso"), ("2", "medio"), ("3", "alto")],
                        help_text="Identificare il livello di sensibilità dei dati conservati o trattati dal fornitore terzo di servizi TIC.",
                        max_length=1,
                        null=True,
                        verbose_name="Sensibilità dei dati conservati dal fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "dependency_level",
                    models.CharField(
                        choices=[
                            ("1", "dipendenza irrilevante"),
                            ("2", "dipendenza modesta"),
                            ("3", "dipendenza significativa"),
                            ("4", "dipendenza totale"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per il livello di dipendenza dal servizio TIC.",
                        max_length=1,
                        verbose_name="Livello di dipendenza dal servizio TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Agreement Details (B2_02)",
                "verbose_name_plural": "Contract Agreement Details (B2_02)",
                "db_table": "ContractAgreementDetails-B2_02",
            },
        ),
    ]
