# Generated by Django 5.1.7 on 2025-03-29 07:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0003_load_iso4217_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="country_code",
            field=django_countries.fields.CountryField(
                default="IT",
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                max_length=2,
                verbose_name="B_01.02.0030\nPaese dell'entità finanziaria",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="country_code",
            field=django_countries.fields.CountryField(
                default="IT",
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                max_length=2,
                verbose_name="B_01.01.0030\nPaese dell'entità finanziaria",
            ),
        ),
    ]
