# Generated by Django 5.1.7 on 2025-03-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0004_alter_financialentity_b1_02_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="EUR",
                help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ContractAgreement",
                to="REGDORA.currency",
                verbose_name="Valuta dell'importo segnalato",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="EUR",
                help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_entities",
                to="REGDORA.currency",
                verbose_name="B_01.02.0100\nValuta",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="EUR",
                help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ThirdPartyVendor",
                to="REGDORA.currency",
                verbose_name="Valuta dell'importo segnalato",
            ),
        ),
    ]
