# Generated by Django 5.1.7 on 2025-03-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0004_contractagreement_b2_01_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="financial_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_agreements",
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità finanziaria",
            ),
        ),
    ]
