# Generated by Django 5.1.7 on 2025-03-29 15:05

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0005_alter_contractagreement_b2_01_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractsigningentity_b3_01",
            options={},
        ),
        migrations.AlterModelOptions(
            name="financialentityserviceprovider_b3_03",
            options={},
        ),
        migrations.AlterModelOptions(
            name="financialentityserviceusage_b4_01",
            options={},
        ),
        migrations.AlterModelOptions(
            name="thirdpartyvendorsigning_b3_02",
            options={},
        ),
        migrations.RemoveField(
            model_name="thirdpartyvendor_b5_01",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="thirdpartyvendor_b5_01",
            name="estimated_annual_cost",
        ),
        migrations.RemoveField(
            model_name="thirdpartyvendor_b5_01",
            name="parent_company_code",
        ),
        migrations.RemoveField(
            model_name="thirdpartyvendor_b5_01",
            name="parent_company_code_type",
        ),
        migrations.AlterField(
            model_name="branch_b1_03",
            name="branch_code",
            field=models.CharField(
                help_text="Identificare una succursale di un'entità finanziaria situata al di fuori del paese d'origine utilizzando un codice univoco per ciascuna succursale.",
                max_length=255,
                unique=True,
                verbose_name="Codice identificativo della succursale (B_01.03.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="branch_b1_03",
            name="branch_country",
            field=models.CharField(
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui la succursale è ubicata.",
                max_length=2,
                verbose_name="Paese della succursale (B_01.03.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="branch_b1_03",
            name="branch_name",
            field=models.CharField(
                help_text="Indicare il nome della succursale.",
                max_length=255,
                verbose_name="Nome della succursale (B_01.03.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="branch_b1_03",
            name="head_office_lei",
            field=models.ForeignKey(
                help_text="Identificare la sede centrale dell'entità finanziaria da cui dipende la succursale utilizzando il LEI.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI della sede centrale dell'entità finanziaria da cui dipende la succursale (B_01.03.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="contract_reference_number",
            field=models.CharField(
                help_text="Identificare l'accordo contrattuale tra l'entità finanziaria e il fornitore terzo diretto di servizi TIC.",
                max_length=255,
                unique=True,
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_02.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("1", "accordo autonomo"),
                    ("2", "accordo contrattuale generale/master"),
                    ("3", "accordo successivo o associato"),
                ],
                help_text="Identificare il tipo di accordo contrattuale.",
                max_length=1,
                verbose_name="Tipo di accordo contrattuale (B_02.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="EUR",
                help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ContractAgreement",
                to="REGDORA.currency",
                verbose_name="Valuta dell'importo segnalato (B_02.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="estimated_annual_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Spese o costi stimati annuali dell'accordo contrattuale per l'anno passato.",
                max_digits=20,
                verbose_name="Spese o costi stimati annuali (B_02.01.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="general_contract_reference",
            field=models.CharField(
                blank=True,
                help_text="Indicare il numero di riferimento dell'accordo contrattuale generale.",
                max_length=255,
                null=True,
                verbose_name="Numero di riferimento dell'accordo contrattuale generale (B_02.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="applicable_law_country",
            field=models.CharField(
                help_text="Indicare il paese del diritto applicabile all'accordo contrattuale.",
                max_length=2,
                verbose_name="Paese del diritto applicabile all'accordo contrattuale (B_02.02.0120)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Come segnalato in B_02.01.0010.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_02.02.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_at_rest_location",
            field=models.CharField(
                blank=True,
                help_text="Indicare il paese di ubicazione dei dati «at rest».",
                max_length=2,
                null=True,
                verbose_name="Ubicazione dei dati «at rest» (conservazione) (B_02.02.0150)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_management_location",
            field=models.CharField(
                blank=True,
                help_text="Indicare il paese di ubicazione della gestione dei dati.",
                max_length=2,
                null=True,
                verbose_name="Ubicazione della gestione dei dati (trattamento) (B_02.02.0160)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_retention",
            field=models.CharField(
                choices=[("1", "Sì"), ("2", "No")],
                help_text="Il servizio TIC riguarda (o prevede) la conservazione dei dati?",
                max_length=1,
                verbose_name="Conservazione dei dati (B_02.02.0140)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_sensitivity",
            field=models.CharField(
                blank=True,
                choices=[("1", "basso"), ("2", "medio"), ("3", "alto")],
                help_text="Identificare il livello di sensibilità dei dati conservati o trattati dal fornitore terzo di servizi TIC.",
                max_length=1,
                null=True,
                verbose_name="Sensibilità dei dati conservati dal fornitore terzo di servizi TIC (B_02.02.0170)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="dependency_level",
            field=models.CharField(
                choices=[
                    ("1", "dipendenza irrilevante"),
                    ("2", "dipendenza modesta"),
                    ("3", "dipendenza significativa"),
                    ("4", "dipendenza totale"),
                ],
                help_text="Utilizzare una delle opzioni indicate per il livello di dipendenza dal servizio TIC.",
                max_length=1,
                verbose_name="Livello di dipendenza dal servizio TIC (B_02.02.0180)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="end_date",
            field=models.DateField(
                help_text="Indicare la data di fine stabilita nell'accordo contrattuale.",
                verbose_name="Data di fine dell'accordo contrattuale (B_02.02.0080)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="financial_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_agreements",
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità finanziaria (B_02.02.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="financial_entity_notice_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte dell'entità finanziaria.",
                null=True,
                verbose_name="Termine di preavviso per l'entità finanziaria (B_02.02.0100)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="function_identifier",
            field=models.CharField(
                help_text="Identificativo della funzione come definito dall'entità finanziaria.",
                max_length=255,
                verbose_name="Identificativo della funzione (B_02.02.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="service_provision_country",
            field=models.CharField(
                help_text="Indicare il paese da cui i servizi TIC sono prestati.",
                max_length=2,
                verbose_name="Paese da cui si prestano i servizi TIC (B_02.02.0130)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="start_date",
            field=models.DateField(
                help_text="Indicare la data di entrata in vigore dell'accordo contrattuale.",
                verbose_name="Data di inizio dell'accordo contrattuale (B_02.02.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="termination_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "risoluzione per scadenza naturale"),
                    (
                        "2",
                        "risoluzione per giusta causa (violazione di leggi/regolamenti)",
                    ),
                    ("3", "risoluzione per giusta causa (impedimenti del fornitore)"),
                    (
                        "4",
                        "risoluzione per giusta causa (gestione e sicurezza dei dati)",
                    ),
                    ("5", "risoluzione su richiesta di un'autorità competente"),
                    ("6", "altro"),
                ],
                help_text="Indicare il motivo della risoluzione o della fine dell'accordo contrattuale.",
                max_length=1,
                null=True,
                verbose_name="Motivo della risoluzione o della fine dell'accordo contrattuale (B_02.02.0090)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="third_party_vendor_code",
            field=models.CharField(
                help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_02.02.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="tic_service_type",
            field=models.CharField(
                choices=[
                    ("1", "Tipo di servizio TIC 1"),
                    ("2", "Tipo di servizio TIC 2"),
                ],
                help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                max_length=1,
                verbose_name="Tipo di servizi TIC (B_02.02.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="vendor_code_type",
            field=models.CharField(
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_02.02.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="vendor_notice_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte del fornitore terzo.",
                null=True,
                verbose_name="Termine di preavviso per il fornitore terzo di servizi TIC (B_02.02.0110)",
            ),
        ),
        migrations.AlterField(
            model_name="contractsigningentity_b3_01",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'impresa.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_03.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="contractsigningentity_b3_01",
            name="signing_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'impresa che firma l'accordo contrattuale utilizzando il LEI o l'EUID.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_signing_entities",
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità che firma l'accordo contrattuale (B_03.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="country_code",
            field=django_countries.fields.CountryField(
                default="IT",
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                max_length=2,
                verbose_name="Paese dell'entità finanziaria (B_01.02.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="EUR",
                help_text="Indicare il codice alfabetico ISO 4217 della valuta...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_entities",
                to="REGDORA.currency",
                verbose_name="Valuta (B_01.02.0100)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="deletion_date",
            field=models.DateField(
                default="9999-12-31",
                help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di cancellazione dell'entità finanziaria dal registro delle informazioni. Se l'entità finanziaria non è stata cancellata, inserire «9999-12-31».",
                verbose_name="Data della cancellazione dal registro delle informazioni (B_01.02.0090)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="entity_name",
            field=models.CharField(
                help_text="Denominazione legale dell'entità finanziaria segnalata nel registro delle informazioni.",
                max_length=255,
                verbose_name="Nome dell'entità finanziaria (B_01.02.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="entity_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.type_of_financial_entity",
                verbose_name="Tipo di entità finanziaria (B_01.02.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="hierarchy",
            field=models.CharField(
                choices=[
                    (
                        "1",
                        "l'entità finanziaria è l'impresa madre capogruppo nel consolidamento",
                    ),
                    (
                        "2",
                        "l'entità finanziaria è l'impresa madre di una parte subconsolidata nel consolidamento",
                    ),
                    (
                        "3",
                        "l'entità finanziaria è un'impresa figlia nel consolidamento e non è un'impresa madre di una parte subconsolidata",
                    ),
                    ("4", "l'entità finanziaria non fa parte di un gruppo"),
                    (
                        "5",
                        "l'entità finanziaria è un fornitore di servizi al quale l'entità finanziaria (o il fornitore terzo di servizi che agisce per suo conto) esternalizza tutte le sue attività operative",
                    ),
                ],
                help_text="Determinare la gerarchia dell'entità finanziaria nel consolidamento utilizzando una delle opzioni nell'elenco chiuso.",
                max_length=1,
                verbose_name="Gerarchia dell'entità finanziaria all'interno del gruppo (se del caso) (B_01.02.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="integration_date",
            field=models.DateField(
                help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di integrazione dell'entità finanziaria nel registro delle informazioni.",
                verbose_name="Data dell'integrazione nel registro delle informazioni (B_01.02.0080)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="last_update_date",
            field=models.DateField(
                help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data dell'ultimo aggiornamento effettuato o dell'ultima modifica apportata nel registro delle informazioni in relazione all'entità finanziaria.",
                verbose_name="Data dell'ultimo aggiornamento (B_01.02.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="lei",
            field=models.CharField(
                help_text="Identificare l'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                max_length=20,
                unique=True,
                verbose_name="LEI dell'entità finanziaria (B_01.02.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="parent_lei",
            field=models.ForeignKey(
                blank=True,
                help_text="Identificare l'impresa madre diretta dell'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_entities",
                to="REGDORA.thirdpartyvendor_b1_01_01",
                verbose_name="LEI dell'impresa madre diretta dell'entità finanziaria (B_01.02.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="total_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valore monetario delle attività totali dell'entità finanziaria come segnalato nel bilancio dell'entità finanziaria dell'esercizio precedente la data dell'ultimo aggiornamento del registro delle informazioni.",
                max_digits=20,
                null=True,
                verbose_name="Valore delle attività totali dell'entità finanziaria (B_01.02.0110)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceprovider_b3_03",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'entità per la prestazione del servizio o dei servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_03.03.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceprovider_b3_03",
            name="service_provider_lei",
            field=models.ForeignKey(
                help_text="Identificare l'entità che fornisce servizi TIC utilizzando il LEI.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità finanziaria che fornisce servizi TIC (B_03.03.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceusage_b4_01",
            name="branch_code",
            field=models.CharField(
                blank=True,
                help_text="Codice identificativo della succursale segnalato in B_01.03.0010.",
                max_length=255,
                null=True,
                verbose_name="Codice identificativo della succursale (B_04.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceusage_b4_01",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Indicare il numero di riferimento dell'accordo contrattuale connesso all'entità finanziaria che si avvale dei servizi TIC prestati.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_04.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceusage_b4_01",
            name="entity_nature",
            field=models.CharField(
                choices=[
                    (
                        "1",
                        "L'entità finanziaria che si avvale del servizio o dei servizi TIC è una succursale dell'entità finanziaria",
                    ),
                    (
                        "2",
                        "L'entità finanziaria che si avvale del servizio o dei servizi TIC non è una succursale",
                    ),
                ],
                help_text="Utilizzare una delle opzioni indicate per la natura dell'entità finanziaria.",
                max_length=1,
                verbose_name="Natura dell'entità finanziaria che si avvale del servizio o dei servizi TIC (B_04.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentityserviceusage_b4_01",
            name="financial_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC utilizzando il LEI.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità finanziaria che si avvale del servizio o dei servizi TIC (B_04.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="authorized_activity",
            field=models.CharField(
                choices=[("1", "Attività A"), ("2", "Attività B")],
                help_text="Una delle attività autorizzate di cui agli atti giuridici sottostanti.",
                max_length=1,
                verbose_name="Attività autorizzata (B_06.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="essentiality",
            field=models.CharField(
                choices=[("1", "sì"), ("2", "no"), ("3", "valutazione non effettuata")],
                help_text="Utilizzare una delle opzioni indicate per la valutazione dell'essenzialità o dell'importanza.",
                max_length=1,
                verbose_name="Valutazione dell'essenzialità o dell'importanza (B_06.01.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="essentiality_reasons",
            field=models.TextField(
                blank=True,
                help_text="Breve spiegazione dei motivi per cui la funzione è stata classificata come essenziale o importante.",
                null=True,
                verbose_name="Motivi dell'essenzialità o dell'importanza (B_06.01.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="financial_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'entità finanziaria utilizzando il LEI.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità finanziaria (B_06.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="function_id",
            field=models.CharField(
                help_text="Identificativo della funzione univoco.",
                max_length=255,
                unique=True,
                verbose_name="Identificativo della funzione (B_06.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="function_name",
            field=models.CharField(
                help_text="Nome della funzione sulla base dell'organizzazione interna dell'entità finanziaria.",
                max_length=255,
                verbose_name="Nome della funzione (B_06.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="impact",
            field=models.CharField(
                choices=[
                    ("1", "basso"),
                    ("2", "medio"),
                    ("3", "alto"),
                    ("4", "valutazione non effettuata"),
                ],
                help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione della funzione.",
                max_length=1,
                verbose_name="Impatto dell'interruzione della funzione (B_06.01.0110)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="last_evaluation_date",
            field=models.DateField(
                help_text="Data dell'ultima valutazione dell'essenzialità o dell'importanza.",
                verbose_name="Data dell'ultima valutazione dell'essenzialità o dell'importanza (B_06.01.0080)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="recovery_point_objective",
            field=models.PositiveIntegerField(
                help_text="Obiettivo di punto di ripristino della funzione in numero di ore.",
                verbose_name="Obiettivo di punto di ripristino della funzione (B_06.01.0100)",
            ),
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="recovery_time_objective",
            field=models.PositiveIntegerField(
                help_text="Obiettivo di tempo di ripristino della funzione in numero di ore.",
                verbose_name="Obiettivo di tempo di ripristino della funzione (B_06.01.0090)",
            ),
        ),
        migrations.AlterField(
            model_name="intragroupcontractagreement_b2_03",
            name="contract_reference_number",
            field=models.CharField(
                help_text="Numero di riferimento dell'accordo contrattuale tra l'entità che si avvale del servizio o dei servizi TIC e il fornitore intragruppo di servizi TIC.",
                max_length=255,
                unique=True,
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_02.03.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="intragroupcontractagreement_b2_03",
            name="linked_contract_reference",
            field=models.ForeignKey(
                help_text="Numero di riferimento dell'accordo contrattuale riguardante l'accordo tra il fornitore intragruppo di servizi TIC e il suo fornitore terzo diretto di servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_group_contracts",
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Accordo contrattuale collegato (B_02.03.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="alternative_vendor",
            field=models.CharField(
                choices=[("1", "sì"), ("2", "no"), ("7", "valutazione non effettuata")],
                help_text="Utilizzare una delle opzioni indicate per l'individuazione di fornitori terzi alternativi di servizi TIC.",
                max_length=1,
                verbose_name="Fornitori terzi alternativi di servizi TIC individuati? (B_07.01.0110)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="alternative_vendor_details",
            field=models.TextField(
                blank=True,
                help_text="Informazioni supplementari sui fornitori terzi alternativi di servizi TIC.",
                null=True,
                verbose_name="Dettagli sui fornitori terzi alternativi di servizi TIC (B_07.01.0120)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="code_type",
            field=models.CharField(
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Come segnalato in B_05.01.0020.",
                max_length=4,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_07.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Come segnalato in B_02.01.0010.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_07.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="exit_plan",
            field=models.CharField(
                choices=[("1", "sì"), ("2", "no")],
                help_text="Utilizzare una delle opzioni indicate per l'esistenza di un piano di uscita.",
                max_length=1,
                verbose_name="Esistenza di un piano di uscita (B_07.01.0080)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="impact",
            field=models.CharField(
                choices=[
                    ("1", "basso"),
                    ("2", "medio"),
                    ("3", "alto"),
                    ("4", "valutazione non effettuata"),
                ],
                help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione dei servizi TIC.",
                max_length=1,
                verbose_name="Impatto dell'interruzione dei servizi TIC (B_07.01.0100)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="last_audit_date",
            field=models.DateField(
                help_text="Data dell'ultimo audit effettuato sugli specifici servizi TIC prestati dal fornitore terzo di servizi TIC.",
                verbose_name="Data dell'ultimo audit sul fornitore TIC (B_07.01.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="reintegration_possibility",
            field=models.CharField(
                choices=[("1", "facile"), ("2", "difficile"), ("3", "molto complessa")],
                help_text="Utilizzare una delle opzioni indicate per la possibilità di reintegrazione del servizio TIC.",
                max_length=1,
                verbose_name="Possibilità di reintegrazione del servizio TIC (B_07.01.0090)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="substitutability",
            field=models.CharField(
                choices=[
                    ("1", "non sostituibile"),
                    ("2", "sostituibilità molto complessa"),
                    ("3", "media complessità in termini di sostituibilità"),
                    ("4", "facilmente sostituibile"),
                ],
                help_text="Utilizzare una delle opzioni indicate per la sostituibilità del fornitore terzo di servizi TIC.",
                max_length=1,
                verbose_name="Sostituibilità del fornitore terzo di servizi TIC (B_07.01.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="substitutability_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "mancanza di alternative reali"),
                    ("2", "difficoltà inerenti alla migrazione"),
                    ("3", "entrambi i motivi di cui ai punti 1 e 2"),
                ],
                help_text="Utilizzare una delle opzioni indicate per il motivo della non sostituibilità.",
                max_length=1,
                null=True,
                verbose_name="Motivo della non sostituibilità del fornitore TIC (B_07.01.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="tic_service_type",
            field=models.CharField(
                choices=[
                    ("1", "Tipo di servizio TIC 1"),
                    ("2", "Tipo di servizio TIC 2"),
                ],
                help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                max_length=1,
                verbose_name="Tipo di servizi TIC (B_07.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="vendor_code",
            field=models.ForeignKey(
                help_text="Come segnalato in B_05.01.0010.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_07.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="code_type",
            field=models.CharField(
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Come segnalato in B_05.01.0020 per tale fornitore terzo di servizi TIC.",
                max_length=4,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.02.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Come segnalato in B_02.01.0010.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_05.02.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="position",
            field=models.PositiveIntegerField(
                help_text="Posizione del fornitore terzo di servizi TIC nella catena di approvvigionamento.",
                verbose_name="Posizione (B_05.02.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="recipient_code",
            field=models.CharField(
                blank=True,
                help_text="Codice identificativo del destinatario dei servizi TIC subappaltati.",
                max_length=255,
                null=True,
                verbose_name="Codice identificativo del destinatario dei servizi TIC subappaltati (B_05.02.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="recipient_code_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati.",
                max_length=4,
                null=True,
                verbose_name="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati (B_05.02.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="tic_service_type",
            field=models.CharField(
                choices=[
                    ("1", "Tipo di servizio TIC 1"),
                    ("2", "Tipo di servizio TIC 2"),
                ],
                help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                max_length=1,
                verbose_name="Tipo di servizi TIC (B_05.02.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="vendor_code",
            field=models.ForeignKey(
                help_text="Come segnalato in B_05.01.0010 per tale fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_05.02.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="availability_date",
            field=models.DateField(
                blank=True,
                help_text="Indicare la data utilizzando il codice ISO 8601 (aaaa-mm-gg) della data di messa a disposizione.",
                null=True,
                verbose_name="Data della messa a disposizione (B_01.01.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="competent_authority",
            field=models.CharField(
                blank=True,
                help_text="Identificare l'autorità competente di cui all'articolo 46 del regolamento (UE) 2022/2554, a disposizione della quale è messo il registro delle informazioni.",
                max_length=255,
                null=True,
                verbose_name="Autorità competente (B_01.01.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="country_code",
            field=django_countries.fields.CountryField(
                default="IT",
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è stata rilasciata l'autorizzazione o è stata effettuata la registrazione dell'entità segnalata nel registro delle informazioni.",
                max_length=2,
                verbose_name="Paese dell'entità finanziaria (B_01.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="entity_name",
            field=models.CharField(
                help_text="Denominazione legale dell'entità finanziaria che mantiene e aggiorna il registro delle informazioni.",
                max_length=255,
                verbose_name="Nome dell'entità finanziaria (B_01.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="entity_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.type_of_financial_entity",
                verbose_name="Tipo di entità finanziaria (B_01.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="lei",
            field=models.CharField(
                help_text="Identificare l'entità finanziaria che mantiene e aggiorna il registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                max_length=20,
                unique=True,
                verbose_name="LEI dell'entità finanziaria (B_01.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="additional_code_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                max_length=4,
                null=True,
                verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC (B_05.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="additional_vendor_code",
            field=models.CharField(
                blank=True,
                help_text="Codice aggiuntivo per identificare il fornitore terzo di servizi TIC, ove disponibile.",
                max_length=255,
                null=True,
                verbose_name="Codice identificativo aggiuntivo del fornitore terzo di servizi TIC (B_05.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="code_type",
            field=models.CharField(
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                max_length=4,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="headquarters_country",
            field=models.CharField(
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è ubicata la sede operativa a livello mondiale del fornitore terzo di servizi TIC.",
                max_length=2,
                verbose_name="Paese della sede centrale del fornitore terzo di servizi TIC (B_05.01.0080)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="latin_name",
            field=models.CharField(
                help_text="Nome del fornitore terzo di servizi TIC in alfabeto latino.",
                max_length=255,
                verbose_name="Nome del fornitore terzo di servizi TIC in alfabeto latino (B_05.01.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="legal_name",
            field=models.CharField(
                help_text="Denominazione legale del fornitore terzo di servizi TIC come iscritta nel registro delle imprese.",
                max_length=255,
                verbose_name="Denominazione legale del fornitore terzo di servizi TIC (B_05.01.0050)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="vendor_code",
            field=models.CharField(
                help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                unique=True,
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_05.01.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    (
                        "1",
                        "persona giuridica, escluse le persone fisiche che agiscono a titolo professionale",
                    ),
                    ("2", "persona fisica che agisce a titolo professionale"),
                ],
                help_text="Utilizzare una delle opzioni indicate per la tipologia di persona.",
                max_length=1,
                verbose_name="Fornitore terzo di servizi TIC - tipologia di persona (B_05.01.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="contract_reference_number",
            field=models.ForeignKey(
                help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dal fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_03.02.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="third_party_vendor_code",
            field=models.CharField(
                help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_03.02.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="vendor_code_type",
            field=models.CharField(
                choices=[
                    ("LEI", "LEI"),
                    ("EUID", "EUID"),
                    ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                    ("IVA", "IVA (Partita IVA)"),
                    ("PNR", "PNR (Numero di Passaporto)"),
                    ("NIN", "NIN (Numero di Identità Nazionale)"),
                ],
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_03.02.0030)",
            ),
        ),
        migrations.AlterModelTable(
            name="contractsigningentity_b3_01",
            table=None,
        ),
        migrations.AlterModelTable(
            name="financialentityserviceprovider_b3_03",
            table=None,
        ),
        migrations.AlterModelTable(
            name="financialentityserviceusage_b4_01",
            table=None,
        ),
        migrations.AlterModelTable(
            name="thirdpartyvendorsigning_b3_02",
            table=None,
        ),
    ]
