# Generated by Django 5.1.7 on 2025-03-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0005_alter_contractagreementdetails_b2_02_financial_entity_lei"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntraGroupContractAgreement_B2_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.CharField(
                        help_text="Numero di riferimento dell'accordo contrattuale tra l'entità che si avvale del servizio o dei servizi TIC e il fornitore intragruppo di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "linked_contract_reference",
                    models.ForeignKey(
                        help_text="Numero di riferimento dell'accordo contrattuale riguardante l'accordo tra il fornitore intragruppo di servizi TIC e il suo fornitore terzo diretto di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intra_group_contracts",
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Accordo contrattuale collegato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intra-Group Contract Agreement (B2_03)",
                "verbose_name_plural": "Intra-Group Contract Agreements (B2_03)",
                "db_table": "IntraGroupContractAgreement-B2_03",
            },
        ),
    ]
