# Generated by Django 5.1.7 on 2025-03-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0006_intragroupcontractagreement_b2_03"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSigningEntity_B3_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signing_entity_lei",
                    models.CharField(
                        help_text="Identificare l'impresa che firma l'accordo contrattuale utilizzando il LEI o l'EUID.",
                        max_length=20,
                        verbose_name="LEI dell'entità che firma l'accordo contrattuale",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'impresa.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Signing Entity (B3_01)",
                "verbose_name_plural": "Contract Signing Entities (B3_01)",
                "db_table": "ContractSigningEntity-B3_01",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntityServiceProvider_B3_03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dall'entità per la prestazione del servizio o dei servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "service_provider_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità che fornisce servizi TIC utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria che fornisce servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity Service Provider (B3_03)",
                "verbose_name_plural": "Financial Entity Service Providers (B3_03)",
                "db_table": "FinancialEntityServiceProvider-B3_03",
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyVendorSigning_B3_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "third_party_vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "vendor_code_type",
                    models.CharField(
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale firmato dal fornitore terzo di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor Signing (B3_02)",
                "verbose_name_plural": "Third-Party Vendor Signings (B3_02)",
                "db_table": "ThirdPartyVendorSigning-B3_02",
            },
        ),
    ]
