# Generated by Django 5.1.7 on 2025-03-29 15:39

import REGDORA.models
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0006_alter_contractsigningentity_b3_01_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thirdpartyvendorsigning_b3_02",
            options={
                "verbose_name": "Third-Party Vendor Signing (B3_02)",
                "verbose_name_plural": "Third-Party Vendor Signings (B3_02)",
            },
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="applicable_law_country",
            field=django_countries.fields.CountryField(
                help_text="Indicare il paese del diritto applicabile all'accordo contrattuale.",
                max_length=2,
                verbose_name="Paese del diritto applicabile all'accordo contrattuale (B_02.02.0120)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_at_rest_location",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Indicare il paese di ubicazione dei dati «at rest».",
                max_length=2,
                null=True,
                verbose_name="Ubicazione dei dati «at rest» (conservazione) (B_02.02.0150)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_management_location",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Indicare il paese di ubicazione della gestione dei dati.",
                max_length=2,
                null=True,
                verbose_name="Ubicazione della gestione dei dati (trattamento) (B_02.02.0160)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="financial_entity_notice_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte dell'entità finanziaria.",
                null=True,
                validators=[
                    REGDORA.models.ContractAgreementDetails_B2_02.validate_notice_period
                ],
                verbose_name="Termine di preavviso per l'entità finanziaria (B_02.02.0100)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="service_provision_country",
            field=django_countries.fields.CountryField(
                help_text="Indicare il paese da cui i servizi TIC sono prestati.",
                max_length=2,
                verbose_name="Paese da cui si prestano i servizi TIC (B_02.02.0130)",
            ),
        ),
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="vendor_notice_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Termine di preavviso per la risoluzione dell'accordo contrattuale da parte del fornitore terzo.",
                null=True,
                validators=[
                    REGDORA.models.ContractAgreementDetails_B2_02.validate_notice_period
                ],
                verbose_name="Termine di preavviso per il fornitore terzo di servizi TIC (B_02.02.0110)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="third_party_vendor_code",
            field=models.ForeignKey(
                help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_03.02.0020)",
            ),
        ),
        migrations.AlterModelTable(
            name="thirdpartyvendorsigning_b3_02",
            table="ThirdPartyVendorSigning-B3_02",
        ),
    ]
