# Generated by Django 5.1.7 on 2025-03-29 15:58

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0007_alter_thirdpartyvendorsigning_b3_02_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="headquarters_country",
            field=django_countries.fields.CountryField(
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è ubicata la sede operativa a livello mondiale del fornitore terzo di servizi TIC.",
                max_length=2,
                verbose_name="Paese della sede centrale del fornitore terzo di servizi TIC (B_05.01.0080)",
            ),
        ),
    ]
