# Generated by Django 5.1.7 on 2025-03-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0007_contractsigningentity_b3_01_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractsigningentity_b3_01",
            name="signing_entity_lei",
            field=models.ForeignKey(
                help_text="Identificare l'impresa che firma l'accordo contrattuale utilizzando il LEI o l'EUID.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_signing_entities",
                to="REGDORA.financialentity_b1_02",
                verbose_name="LEI dell'entità che firma l'accordo contrattuale",
            ),
        ),
    ]
