# Generated by Django 5.1.7 on 2025-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0008_alter_thirdpartyvendor_b5_01_headquarters_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="last_audit_date",
            field=models.DateField(
                blank=True,
                help_text="Data dell'ultimo audit effettuato sugli specifici servizi TIC prestati dal fornitore terzo di servizi TIC.",
                null=True,
                verbose_name="Data dell'ultimo audit sul fornitore TIC (B_07.01.0070)",
            ),
        ),
    ]
