# Generated by Django 5.1.7 on 2025-03-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0008_alter_contractsigningentity_b3_01_signing_entity_lei"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyVendor_B5_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=255,
                        unique=True,
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "additional_vendor_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice aggiuntivo per identificare il fornitore terzo di servizi TIC, ove disponibile.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo aggiuntivo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "additional_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Denominazione legale del fornitore terzo di servizi TIC come iscritta nel registro delle imprese.",
                        max_length=255,
                        verbose_name="Denominazione legale del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        help_text="Nome del fornitore terzo di servizi TIC in alfabeto latino.",
                        max_length=255,
                        verbose_name="Nome del fornitore terzo di servizi TIC in alfabeto latino",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "persona giuridica, escluse le persone fisiche che agiscono a titolo professionale",
                            ),
                            ("2", "persona fisica che agisce a titolo professionale"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la tipologia di persona.",
                        max_length=1,
                        verbose_name="Fornitore terzo di servizi TIC - tipologia di persona",
                    ),
                ),
                (
                    "headquarters_country",
                    models.CharField(
                        help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui è ubicata la sede operativa a livello mondiale del fornitore terzo di servizi TIC.",
                        max_length=2,
                        verbose_name="Paese della sede centrale del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Indicare il codice alfabetico ISO 4217 della valuta utilizzata per esprimere l'importo in B_05.01.0100.",
                        max_length=3,
                        null=True,
                        verbose_name="Valuta dell'importo segnalato",
                    ),
                ),
                (
                    "estimated_annual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Spese o costi stimati annuali per l'utilizzo dei servizi TIC prestati dal fornitore terzo di servizi TIC.",
                        max_digits=20,
                        null=True,
                        verbose_name="Spese o costi stimati annuali totali del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "parent_company_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo dell'impresa madre capogruppo del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "parent_company_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice per identificare l'impresa madre capogruppo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-Party Vendor (B5_01)",
                "verbose_name_plural": "Third-Party Vendors (B5_01)",
                "db_table": "ThirdPartyVendor-B5_01",
            },
        ),
        migrations.CreateModel(
            name="FinancialEntityServiceUsage_B4_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_nature",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "l'entità finanziaria che si avvale del servizio o dei servizi TIC è una succursale dell'entità finanziaria",
                            ),
                            (
                                "2",
                                "l'entità finanziaria che si avvale del servizio o dei servizi TIC non è una succursale",
                            ),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la natura dell'entità finanziaria.",
                        max_length=1,
                        verbose_name="Natura dell'entità finanziaria che si avvale del servizio o dei servizi TIC",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice identificativo della succursale segnalato in B_01.03.0010.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo della succursale",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Indicare il numero di riferimento dell'accordo contrattuale connesso all'entità finanziaria che si avvale dei servizi TIC prestati.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità finanziaria che si avvale del servizio o dei servizi TIC utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria che si avvale del servizio o dei servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Entity Service Usage (B4_01)",
                "verbose_name_plural": "Financial Entity Service Usages (B4_01)",
                "db_table": "FinancialEntityServiceUsage-B4_01",
            },
        ),
        migrations.CreateModel(
            name="FunctionIdentification_B6_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_id",
                    models.CharField(
                        help_text="Identificativo della funzione univoco.",
                        max_length=255,
                        unique=True,
                        verbose_name="Identificativo della funzione",
                    ),
                ),
                (
                    "authorized_activity",
                    models.CharField(
                        choices=[("1", "Attività A"), ("2", "Attività B")],
                        help_text="Una delle attività autorizzate di cui agli atti giuridici sottostanti.",
                        max_length=1,
                        verbose_name="Attività autorizzata",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Nome della funzione sulla base dell'organizzazione interna dell'entità finanziaria.",
                        max_length=255,
                        verbose_name="Nome della funzione",
                    ),
                ),
                (
                    "essentiality",
                    models.CharField(
                        choices=[
                            ("1", "sì"),
                            ("2", "no"),
                            ("3", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la valutazione dell'essenzialità o dell'importanza.",
                        max_length=1,
                        verbose_name="Valutazione dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "essentiality_reasons",
                    models.TextField(
                        blank=True,
                        help_text="Breve spiegazione dei motivi per cui la funzione è stata classificata come essenziale o importante.",
                        null=True,
                        verbose_name="Motivi dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "last_evaluation_date",
                    models.DateField(
                        help_text="Data dell'ultima valutazione dell'essenzialità o dell'importanza.",
                        verbose_name="Data dell'ultima valutazione dell'essenzialità o dell'importanza",
                    ),
                ),
                (
                    "recovery_time_objective",
                    models.PositiveIntegerField(
                        help_text="Obiettivo di tempo di ripristino della funzione in numero di ore.",
                        verbose_name="Obiettivo di tempo di ripristino della funzione",
                    ),
                ),
                (
                    "recovery_point_objective",
                    models.PositiveIntegerField(
                        help_text="Obiettivo di punto di ripristino della funzione in numero di ore.",
                        verbose_name="Obiettivo di punto di ripristino della funzione",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("1", "basso"),
                            ("2", "medio"),
                            ("3", "alto"),
                            ("4", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione della funzione.",
                        max_length=1,
                        verbose_name="Impatto dell'interruzione della funzione",
                    ),
                ),
                (
                    "financial_entity_lei",
                    models.ForeignKey(
                        help_text="Identificare l'entità finanziaria utilizzando il LEI.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.financialentity_b1_02",
                        verbose_name="LEI dell'entità finanziaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Function Identification (B6_01)",
                "verbose_name_plural": "Function Identifications (B6_01)",
                "db_table": "FunctionIdentification-B6_01",
            },
        ),
        migrations.CreateModel(
            name="SupplyChain_B5_02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Come segnalato in B_05.01.0020 per tale fornitore terzo di servizi TIC.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Posizione del fornitore terzo di servizi TIC nella catena di approvvigionamento.",
                        verbose_name="Posizione",
                    ),
                ),
                (
                    "recipient_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice identificativo del destinatario dei servizi TIC subappaltati.",
                        max_length=255,
                        null=True,
                        verbose_name="Codice identificativo del destinatario dei servizi TIC subappaltati",
                    ),
                ),
                (
                    "recipient_code_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati.",
                        max_length=4,
                        null=True,
                        verbose_name="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "vendor_code",
                    models.ForeignKey(
                        help_text="Come segnalato in B_05.01.0010 per tale fornitore terzo di servizi TIC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.thirdpartyvendor_b5_01",
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Chain (B5_02)",
                "verbose_name_plural": "Supply Chains (B5_02)",
                "db_table": "SupplyChain-B5_02",
            },
        ),
        migrations.CreateModel(
            name="ServiceEvaluation_B7_01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("LEI", "LEI"),
                            ("EUID", "EUID"),
                            ("CRN", "CRN (Codice di Registrazione delle Imprese)"),
                            ("IVA", "IVA (Partita IVA)"),
                            ("PNR", "PNR (Numero di Passaporto)"),
                            ("NIN", "NIN (Numero di Identità Nazionale)"),
                        ],
                        help_text="Come segnalato in B_05.01.0020.",
                        max_length=4,
                        verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "tic_service_type",
                    models.CharField(
                        choices=[
                            ("1", "Tipo di servizio TIC 1"),
                            ("2", "Tipo di servizio TIC 2"),
                        ],
                        help_text="Uno dei tipi di servizi TIC di cui all'allegato III.",
                        max_length=1,
                        verbose_name="Tipo di servizi TIC",
                    ),
                ),
                (
                    "substitutability",
                    models.CharField(
                        choices=[
                            ("1", "non sostituibile"),
                            ("2", "sostituibilità molto complessa"),
                            ("3", "media complessità in termini di sostituibilità"),
                            ("4", "facilmente sostituibile"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la sostituibilità del fornitore terzo di servizi TIC.",
                        max_length=1,
                        verbose_name="Sostituibilità del fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "substitutability_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "mancanza di alternative reali"),
                            ("2", "difficoltà inerenti alla migrazione"),
                            ("3", "entrambi i motivi di cui ai punti 1 e 2"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per il motivo della non sostituibilità.",
                        max_length=1,
                        null=True,
                        verbose_name="Motivo per cui il fornitore terzo di servizi TIC è considerato non sostituibile o difficilmente sostituibile",
                    ),
                ),
                (
                    "last_audit_date",
                    models.DateField(
                        help_text="Data dell'ultimo audit effettuato sugli specifici servizi TIC prestati dal fornitore terzo di servizi TIC.",
                        verbose_name="Data dell'ultimo audit sul fornitore terzo di servizi TIC",
                    ),
                ),
                (
                    "exit_plan",
                    models.CharField(
                        choices=[("1", "sì"), ("2", "no")],
                        help_text="Utilizzare una delle opzioni indicate per l'esistenza di un piano di uscita.",
                        max_length=1,
                        verbose_name="Esistenza di un piano di uscita",
                    ),
                ),
                (
                    "reintegration_possibility",
                    models.CharField(
                        choices=[
                            ("1", "facile"),
                            ("2", "difficile"),
                            ("3", "molto complessa"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per la possibilità di reintegrazione del servizio TIC.",
                        max_length=1,
                        verbose_name="Possibilità di reintegrazione del servizio TIC previsto dal contratto",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("1", "basso"),
                            ("2", "medio"),
                            ("3", "alto"),
                            ("4", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'impatto dell'interruzione dei servizi TIC.",
                        max_length=1,
                        verbose_name="Impatto dell'interruzione dei servizi TIC",
                    ),
                ),
                (
                    "alternative_vendor",
                    models.CharField(
                        choices=[
                            ("1", "sì"),
                            ("2", "no"),
                            ("7", "valutazione non effettuata"),
                        ],
                        help_text="Utilizzare una delle opzioni indicate per l'individuazione di fornitori terzi alternativi di servizi TIC.",
                        max_length=1,
                        verbose_name="Sono stati individuati fornitori terzi alternativi di servizi TIC?",
                    ),
                ),
                (
                    "alternative_vendor_details",
                    models.TextField(
                        blank=True,
                        help_text="Informazioni supplementari sui fornitori terzi alternativi di servizi TIC.",
                        null=True,
                        verbose_name="Individuazione di fornitori terzi alternativi di servizi TIC",
                    ),
                ),
                (
                    "contract_reference_number",
                    models.ForeignKey(
                        help_text="Come segnalato in B_02.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.contractagreement_b2_01",
                        verbose_name="Numero di riferimento dell'accordo contrattuale",
                    ),
                ),
                (
                    "vendor_code",
                    models.ForeignKey(
                        help_text="Come segnalato in B_05.01.0010.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="REGDORA.thirdpartyvendor_b5_01",
                        verbose_name="Codice identificativo del fornitore terzo di servizi TIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Evaluation (B7_01)",
                "verbose_name_plural": "Service Evaluations (B7_01)",
                "db_table": "ServiceEvaluation-B7_01",
            },
        ),
    ]
