# Generated by Django 5.1.7 on 2025-03-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0009_alter_serviceevaluation_b7_01_last_audit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="third_party_vendor_code",
            field=models.ForeignKey(
                help_text="Codice per identificare il fornitore terzo di servizi TIC.",
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_02.02.0030)",
            ),
        ),
    ]
