# Generated by Django 5.1.7 on 2025-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "REGDORA",
            "0010_alter_contractagreementdetails_b2_02_third_party_vendor_code",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ICTService",
            fields=[
                (
                    "service_id",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identificativo",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        max_length=255, verbose_name="Tipo di servizi TIC"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrizione")),
            ],
        ),
    ]
