# Generated by Django 5.1.7 on 2025-03-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0011_ictservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="tic_service_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di servizio TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ICT_Service_Type",
                to="REGDORA.ictservice",
                verbose_name="Tipo di servizi TIC (B_02.02.0060)",
            ),
        ),
    ]
