# Generated by Django 5.1.7 on 2025-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0013_alter_serviceevaluation_b7_01_tic_service_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="tic_service_type",
            field=models.CharField(
                help_text="Come segnalato in B_05.01.0020.",
                max_length=3,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_07.01.0030)",
            ),
        ),
    ]
