# Generated by Django 5.1.7 on 2025-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0015_alter_serviceevaluation_b7_01_tic_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        verbose_name="Codice dell'autorità competente",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione dell'autorità competente",
                    ),
                ),
            ],
        ),
    ]
