# Generated by Django 5.1.7 on 2025-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0016_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authority",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                verbose_name="Codice dell'autorità competente",
            ),
        ),
    ]
