# Generated by Django 5.1.7 on 2025-03-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0018_alter_thirdpartyvendor_b1_01_01_competent_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="entity_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di entità finanziaria utilizzando una delle opzioni presenti nell'elenco chiuso.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.type_of_financial_entity",
                verbose_name="Tipo di entità finanziaria (B_01.01.0040)",
            ),
        ),
    ]
