# Generated by Django 5.1.7 on 2025-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0019_alter_thirdpartyvendor_b1_01_01_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="competent_authority",
            field=models.CharField(
                blank=True,
                help_text="Identificare l'autorità competente di cui all'articolo 46 del regolamento (UE) 2022/2554, a disposizione della quale è messo il registro delle informazioni.",
                max_length=255,
                null=True,
                verbose_name="Autorità competente (B_01.01.0050)",
            ),
        ),
    ]
