# Generated by Django 5.1.7 on 2025-03-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0020_alter_thirdpartyvendor_b1_01_01_competent_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="competent_authority",
            field=models.ForeignKey(
                blank=True,
                help_text="Identificare l'autorità competente di cui all'articolo 46 del regolamento (UE) 2022/2554, a disposizione della quale è messo il registro delle informazioni.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.authority",
                verbose_name="Autorità competente (B_01.01.0050)",
            ),
        ),
    ]
