# Generated by Django 5.1.7 on 2025-03-31 11:22

import REGDORA.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0021_alter_thirdpartyvendor_b1_01_01_competent_authority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract_types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=1,
                        unique=True,
                        verbose_name="Codice del tipo contratto",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Descrizione del tipo contratto"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="branch_b1_03",
            name="branch_code",
            field=models.CharField(
                help_text="Identificare una succursale di un'entità finanziaria situata al di fuori del paese d'origine utilizzando un codice univoco per ciascuna succursale.",
                max_length=20,
                unique=True,
                verbose_name="Codice identificativo della succursale (B_01.03.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="financialentity_b1_02",
            name="lei",
            field=models.CharField(
                help_text="Identificare l'entità finanziaria segnalata nel registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                max_length=20,
                unique=True,
                validators=[REGDORA.utils.validate_lei],
                verbose_name="LEI dell'entità finanziaria (B_01.02.0010)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b1_01_01",
            name="lei",
            field=models.CharField(
                help_text="Identificare l'entità finanziaria che mantiene e aggiorna il registro delle informazioni utilizzando il LEI, codice alfanumerico di 20 caratteri conforme alla norma ISO 17442.",
                max_length=20,
                unique=True,
                validators=[REGDORA.utils.validate_lei],
                verbose_name="LEI dell'entità finanziaria (B_01.01.0010)",
            ),
        ),
    ]
