# Generated by Django 5.1.7 on 2025-03-31 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0022_contract_types_alter_branch_b1_03_branch_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreement_b2_01",
            name="contract_type",
            field=models.ForeignKey(
                help_text="Identificare il tipo di accordo contrattuale.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.contract_types",
                verbose_name="Tipo di accordo contrattuale (B_02.01.0020)",
            ),
        ),
    ]
