# Generated by Django 5.1.7 on 2025-03-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0023_alter_contractagreement_b2_01_contract_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="contract_reference_number",
            field=models.OneToOneField(
                help_text="Come segnalato in B_02.01.0010.",
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.contractagreement_b2_01",
                verbose_name="Numero di riferimento dell'accordo contrattuale (B_02.02.0010)",
            ),
        ),
    ]
