# Generated by Django 5.1.7 on 2025-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "REGDORA",
            "0024_alter_contractagreementdetails_b2_02_contract_reference_number",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependency_levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=1,
                        unique=True,
                        verbose_name="Codice del livello di dipendenza",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione del livello di dipendenza",
                    ),
                ),
            ],
        ),
    ]
