# Generated by Django 5.1.7 on 2025-03-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0025_dependency_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="dependency_level",
            field=models.ForeignKey(
                help_text="Utilizzare una delle opzioni indicate per il livello di dipendenza dal servizio TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.dependency_levels",
                verbose_name="Livello di dipendenza dal servizio TIC (B_02.02.0180)",
            ),
        ),
    ]
