# Generated by Django 5.1.7 on 2025-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0026_alter_contractagreementdetails_b2_02_dependency_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_sensitivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=1,
                        unique=True,
                        verbose_name="Codice di sensibilità dei dati",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione della di sensibilità dei dati",
                    ),
                ),
            ],
        ),
    ]
