# Generated by Django 5.1.7 on 2025-03-31 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0027_data_sensitivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="data_sensitivity",
            field=models.ForeignKey(
                blank=True,
                help_text="Identificare il livello di sensibilità dei dati conservati o trattati dal fornitore terzo di servizi TIC.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.data_sensitivity",
                verbose_name="Sensibilità dei dati conservati dal fornitore terzo di servizi TIC (B_02.02.0170)",
            ),
        ),
    ]
