# Generated by Django 5.1.7 on 2025-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0028_alter_contractagreementdetails_b2_02_data_sensitivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Termination_reasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=1,
                        unique=True,
                        verbose_name="Codice del motivo di chiusura del contratto",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione del motivo di chiusura del contratto",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="data_sensitivity",
            name="description",
            field=models.CharField(
                max_length=255,
                verbose_name="Descrizione del livello di sensibilità dei dati",
            ),
        ),
    ]
