# Generated by Django 5.1.7 on 2025-03-31 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0029_termination_reasons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="termination_reason",
            field=models.ForeignKey(
                blank=True,
                help_text="Indicare il motivo della risoluzione o della fine dell'accordo contrattuale.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.termination_reasons",
                verbose_name="Motivo della risoluzione o della fine dell'accordo contrattuale (B_02.02.0090)",
            ),
        ),
    ]
