# Generated by Django 5.1.7 on 2025-03-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0030_alter_contractagreementdetails_b2_02_termination_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="function_identifier",
            field=models.ForeignKey(
                help_text="Identificativo della funzione come definito dall'entità finanziaria.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.functionidentification_b6_01",
                verbose_name="Identificativo della funzione (B_02.02.0050)",
            ),
        ),
    ]
