# Generated by Django 5.1.7 on 2025-04-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0031_alter_contractagreementdetails_b2_02_function_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentityserviceusage_b4_01",
            name="branch_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Codice identificativo della succursale segnalato in B_01.03.0010.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="REGDORA.branch_b1_03",
                verbose_name="Codice identificativo della succursale (B_04.01.0040)",
            ),
        ),
    ]
