# Generated by Django 5.1.7 on 2025-04-01 09:38

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0032_alter_financialentityserviceusage_b4_01_branch_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch_b1_03",
            name="branch_country",
            field=django_countries.fields.CountryField(
                help_text="Indicare il codice ISO 3166-1 alpha-2 del paese in cui la succursale è ubicata.",
                max_length=2,
                verbose_name="Paese della succursale (B_01.03.0040)",
            ),
        ),
    ]
