# Generated by Django 5.1.7 on 2025-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0033_alter_branch_b1_03_branch_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor_code_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="Codice della tipologia del codice identificativo del fornitore",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrizione della tipologia del codice identificativo del fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor code type",
                "verbose_name_plural": "Types of vendor code",
                "db_table": "Vendor_code_type",
            },
        ),
    ]
