# Generated by Django 5.1.7 on 2025-04-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0034_vendor_code_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreementdetails_b2_02",
            name="vendor_code_type",
            field=models.ForeignKey(
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Code_type_for_vendor_in_02_02",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_02.02.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevaluation_b7_01",
            name="code_type",
            field=models.ForeignKey(
                help_text="Come segnalato in B_05.01.0020.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_07_01",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_07.01.0030)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="code_type",
            field=models.ForeignKey(
                help_text="Come segnalato in B_05.01.0020 per tale fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.02.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="recipient_code_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_recipient",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il destinatario dei servizi TIC subappaltati (B_05.02.0070)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="additional_code_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_05010040",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC (B_05.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="code_type",
            field=models.ForeignKey(
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_05_01_0020",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.01.0020)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="vendor_code_type",
            field=models.ForeignKey(
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_03_02",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_03.02.0030)",
            ),
        ),
    ]
