# Generated by Django 5.1.7 on 2025-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "REGDORA",
            "0035_alter_contractagreementdetails_b2_02_vendor_code_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="additional_code_type",
            field=models.CharField(
                blank=True,
                help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                max_length=4,
                null=True,
                verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC (B_05.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="code_type",
            field=models.CharField(
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                max_length=4,
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.01.0020)",
            ),
        ),
    ]
