# Generated by Django 5.1.7 on 2025-04-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0036_alter_thirdpartyvendor_b5_01_additional_code_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="additional_code_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_05010040",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice identificativo aggiuntivo per identificare il fornitore terzo di servizi TIC (B_05.01.0040)",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartyvendor_b5_01",
            name="code_type",
            field=models.ForeignKey(
                help_text="Tipo di codice per identificare il fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Vendor_code_type_for_05_01_0020",
                to="REGDORA.vendor_code_type",
                verbose_name="Tipo di codice per identificare il fornitore terzo di servizi TIC (B_05.01.0020)",
            ),
        ),
    ]
