# Generated by Django 5.1.7 on 2025-04-01 15:06

import REGDORA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0037_alter_thirdpartyvendor_b5_01_additional_code_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractagreementdetails_b2_02",
            name="vendor_code_type",
        ),
        migrations.AlterField(
            model_name="functionidentification_b6_01",
            name="function_id",
            field=models.CharField(
                help_text="Identificativo della funzione univoco.",
                max_length=255,
                unique=True,
                validators=[
                    REGDORA.models.FunctionIdentification_B6_01.validate_function_id
                ],
                verbose_name="Identificativo della funzione (B_06.01.0010)",
            ),
        ),
        migrations.AddConstraint(
            model_name="functionidentification_b6_01",
            constraint=models.UniqueConstraint(
                fields=("financial_entity_lei", "function_name", "authorized_activity"),
                name="unique_financial_entity_function_activity",
            ),
        ),
    ]
