# Generated by Django 5.1.7 on 2025-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "REGDORA",
            "0038_remove_contractagreementdetails_b2_02_vendor_code_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thirdpartyvendorsigning_b3_02",
            name="vendor_code_type",
        ),
    ]
