# Generated by Django 5.1.7 on 2025-04-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REGDORA", "0039_remove_thirdpartyvendorsigning_b3_02_vendor_code_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplychain_b5_02",
            name="code_type",
        ),
        migrations.RemoveField(
            model_name="supplychain_b5_02",
            name="recipient_code_type",
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="recipient_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Codice identificativo del destinatario dei servizi TIC subappaltati.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_chain_recipient_codes",
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del destinatario dei servizi TIC subappaltati (B_05.02.0060)",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain_b5_02",
            name="vendor_code",
            field=models.ForeignKey(
                help_text="Come segnalato in B_05.01.0010 per tale fornitore terzo di servizi TIC.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_chain_vendor_codes",
                to="REGDORA.thirdpartyvendor_b5_01",
                verbose_name="Codice identificativo del fornitore terzo di servizi TIC (B_05.02.0030)",
            ),
        ),
    ]
