from django.core.management.base import BaseCommand
from REGDORA.models import Currency

# ISO 4217 currency data as of latest standard
CURRENCY_DATA = [
    {'code': 'AED', 'name': 'UAE Dirham', 'numeric_code': 784, 'symbol': 'د.إ'},
    {'code': 'AFN', 'name': 'Afghan Afghani', 'numeric_code': 971, 'symbol': '؋'},
    {'code': 'ALL', 'name': 'Albanian Lek', 'numeric_code': 8, 'symbol': 'L'},
    {'code': 'AMD', 'name': 'Armenian Dram', 'numeric_code': 51, 'symbol': '֏'},
    {'code': 'ANG', 'name': 'Netherlands Antillean Guilder', 'numeric_code': 532, 'symbol': 'ƒ'},
    {'code': 'AOA', 'name': 'Angolan Kwanza', 'numeric_code': 973, 'symbol': 'Kz'},
    {'code': 'ARS', 'name': 'Argentine Peso', 'numeric_code': 32, 'symbol': '$'},
    {'code': 'AUD', 'name': 'Australian Dollar', 'numeric_code': 36, 'symbol': '$'},
    {'code': 'AWG', 'name': 'Aruban Florin', 'numeric_code': 533, 'symbol': 'ƒ'},
    {'code': 'AZN', 'name': 'Azerbaijani Manat', 'numeric_code': 944, 'symbol': '₼'},
    {'code': 'BAM', 'name': 'Bosnia-Herzegovina Convertible Mark', 'numeric_code': 977, 'symbol': 'KM'},
    {'code': 'BBD', 'name': 'Barbadian Dollar', 'numeric_code': 52, 'symbol': '$'},
    {'code': 'BDT', 'name': 'Bangladeshi Taka', 'numeric_code': 50, 'symbol': '৳'},
    {'code': 'BGN', 'name': 'Bulgarian Lev', 'numeric_code': 975, 'symbol': 'лв'},
    {'code': 'BHD', 'name': 'Bahraini Dinar', 'numeric_code': 48, 'symbol': '.د.ب'},
    {'code': 'BIF', 'name': 'Burundian Franc', 'numeric_code': 108, 'symbol': 'FBu'},
    {'code': 'BMD', 'name': 'Bermudan Dollar', 'numeric_code': 60, 'symbol': '$'},
    {'code': 'BND', 'name': 'Brunei Dollar', 'numeric_code': 96, 'symbol': '$'},
    {'code': 'BOB', 'name': 'Bolivian Boliviano', 'numeric_code': 68, 'symbol': '$b'},
    {'code': 'BRL', 'name': 'Brazilian Real', 'numeric_code': 986, 'symbol': 'R$'},
    {'code': 'BSD', 'name': 'Bahamian Dollar', 'numeric_code': 44, 'symbol': '$'},
    {'code': 'BTN', 'name': 'Bhutanese Ngultrum', 'numeric_code': 64, 'symbol': 'Nu.'},
    {'code': 'BWP', 'name': 'Botswanan Pula', 'numeric_code': 72, 'symbol': 'P'},
    {'code': 'BYN', 'name': 'Belarusian Ruble', 'numeric_code': 933, 'symbol': 'Br'},
    {'code': 'BZD', 'name': 'Belize Dollar', 'numeric_code': 84, 'symbol': 'BZ$'},
    {'code': 'CAD', 'name': 'Canadian Dollar', 'numeric_code': 124, 'symbol': '$'},
    {'code': 'CDF', 'name': 'Congolese Franc', 'numeric_code': 976, 'symbol': 'FC'},
    {'code': 'CHF', 'name': 'Swiss Franc', 'numeric_code': 756, 'symbol': 'CHF'},
    {'code': 'CLP', 'name': 'Chilean Peso', 'numeric_code': 152, 'symbol': '$'},
    {'code': 'CNY', 'name': 'Chinese Yuan', 'numeric_code': 156, 'symbol': '¥'},
    {'code': 'COP', 'name': 'Colombian Peso', 'numeric_code': 170, 'symbol': '$'},
    {'code': 'CRC', 'name': 'Costa Rican Colón', 'numeric_code': 188, 'symbol': '₡'},
    {'code': 'CUP', 'name': 'Cuban Peso', 'numeric_code': 192, 'symbol': '₱'},
    {'code': 'CVE', 'name': 'Cape Verdean Escudo', 'numeric_code': 132, 'symbol': '$'},
    {'code': 'CZK', 'name': 'Czech Koruna', 'numeric_code': 203, 'symbol': 'Kč'},
    {'code': 'DJF', 'name': 'Djiboutian Franc', 'numeric_code': 262, 'symbol': 'Fdj'},
    {'code': 'DKK', 'name': 'Danish Krone', 'numeric_code': 208, 'symbol': 'kr'},
    {'code': 'DOP', 'name': 'Dominican Peso', 'numeric_code': 214, 'symbol': 'RD$'},
    {'code': 'DZD', 'name': 'Algerian Dinar', 'numeric_code': 12, 'symbol': 'دج'},
    {'code': 'EGP', 'name': 'Egyptian Pound', 'numeric_code': 818, 'symbol': '£'},
    {'code': 'ERN', 'name': 'Eritrean Nakfa', 'numeric_code': 232, 'symbol': 'Nfk'},
    {'code': 'ETB', 'name': 'Ethiopian Birr', 'numeric_code': 230, 'symbol': 'Br'},
    {'code': 'EUR', 'name': 'Euro', 'numeric_code': 978, 'symbol': '€'},
    {'code': 'FJD', 'name': 'Fijian Dollar', 'numeric_code': 242, 'symbol': '$'},
    {'code': 'FKP', 'name': 'Falkland Islands Pound', 'numeric_code': 238, 'symbol': '£'},
    {'code': 'GBP', 'name': 'British Pound', 'numeric_code': 826, 'symbol': '£'},
    {'code': 'GEL', 'name': 'Georgian Lari', 'numeric_code': 981, 'symbol': '₾'},
    {'code': 'GHS', 'name': 'Ghanaian Cedi', 'numeric_code': 936, 'symbol': 'GH₵'},
    {'code': 'GIP', 'name': 'Gibraltar Pound', 'numeric_code': 292, 'symbol': '£'},
    {'code': 'GMD', 'name': 'Gambian Dalasi', 'numeric_code': 270, 'symbol': 'D'},
    {'code': 'GNF', 'name': 'Guinean Franc', 'numeric_code': 324, 'symbol': 'FG'},
    {'code': 'GTQ', 'name': 'Guatemalan Quetzal', 'numeric_code': 320, 'symbol': 'Q'},
    {'code': 'GYD', 'name': 'Guyanaese Dollar', 'numeric_code': 328, 'symbol': '$'},
    {'code': 'HKD', 'name': 'Hong Kong Dollar', 'numeric_code': 344, 'symbol': '$'},
    {'code': 'HNL', 'name': 'Honduran Lempira', 'numeric_code': 340, 'symbol': 'L'},
    {'code': 'HRK', 'name': 'Croatian Kuna', 'numeric_code': 191, 'symbol': 'kn'},
    {'code': 'HTG', 'name': 'Haitian Gourde', 'numeric_code': 332, 'symbol': 'G'},
    {'code': 'HUF', 'name': 'Hungarian Forint', 'numeric_code': 348, 'symbol': 'Ft'},
    {'code': 'IDR', 'name': 'Indonesian Rupiah', 'numeric_code': 360, 'symbol': 'Rp'},
    {'code': 'ILS', 'name': 'Israeli New Shekel', 'numeric_code': 376, 'symbol': '₪'},
    {'code': 'INR', 'name': 'Indian Rupee', 'numeric_code': 356, 'symbol': '₹'},
    {'code': 'IQD', 'name': 'Iraqi Dinar', 'numeric_code': 368, 'symbol': 'ع.د'},
    {'code': 'IRR', 'name': 'Iranian Rial', 'numeric_code': 364, 'symbol': '﷼'},
    {'code': 'ISK', 'name': 'Icelandic Króna', 'numeric_code': 352, 'symbol': 'kr'},
    {'code': 'JMD', 'name': 'Jamaican Dollar', 'numeric_code': 388, 'symbol': 'J$'},
    {'code': 'JOD', 'name': 'Jordanian Dinar', 'numeric_code': 400, 'symbol': 'JD'},
    {'code': 'JPY', 'name': 'Japanese Yen', 'numeric_code': 392, 'symbol': '¥'},
    {'code': 'KES', 'name': 'Kenyan Shilling', 'numeric_code': 404, 'symbol': 'KSh'},
    {'code': 'KGS', 'name': 'Kyrgystani Som', 'numeric_code': 417, 'symbol': 'лв'},
    {'code': 'KHR', 'name': 'Cambodian Riel', 'numeric_code': 116, 'symbol': '៛'},
    {'code': 'KMF', 'name': 'Comorian Franc', 'numeric_code': 174, 'symbol': 'CF'},
    {'code': 'KPW', 'name': 'North Korean Won', 'numeric_code': 408, 'symbol': '₩'},
    {'code': 'KRW', 'name': 'South Korean Won', 'numeric_code': 410, 'symbol': '₩'},
    {'code': 'KWD', 'name': 'Kuwaiti Dinar', 'numeric_code': 414, 'symbol': 'KD'},
    {'code': 'KYD', 'name': 'Cayman Islands Dollar', 'numeric_code': 136, 'symbol': '$'},
    {'code': 'KZT', 'name': 'Kazakhstani Tenge', 'numeric_code': 398, 'symbol': 'лв'},
    {'code': 'LAK', 'name': 'Laotian Kip', 'numeric_code': 418, 'symbol': '₭'},
    {'code': 'LBP', 'name': 'Lebanese Pound', 'numeric_code': 422, 'symbol': '£'},
    {'code': 'LKR', 'name': 'Sri Lankan Rupee', 'numeric_code': 144, 'symbol': '₨'},
    {'code': 'LRD', 'name': 'Liberian Dollar', 'numeric_code': 430, 'symbol': '$'},
    {'code': 'LSL', 'name': 'Lesotho Loti', 'numeric_code': 426, 'symbol': 'L'},
    {'code': 'LYD', 'name': 'Libyan Dinar', 'numeric_code': 434, 'symbol': 'LD'},
    {'code': 'MAD', 'name': 'Moroccan Dirham', 'numeric_code': 504, 'symbol': 'MAD'},
    {'code': 'MDL', 'name': 'Moldovan Leu', 'numeric_code': 498, 'symbol': 'L'},
    {'code': 'MGA', 'name': 'Malagasy Ariary', 'numeric_code': 969, 'symbol': 'Ar'},
    {'code': 'MKD', 'name': 'Macedonian Denar', 'numeric_code': 807, 'symbol': 'ден'},
    {'code': 'MMK', 'name': 'Myanmar Kyat', 'numeric_code': 104, 'symbol': 'K'},
    {'code': 'MNT', 'name': 'Mongolian Tugrik', 'numeric_code': 496, 'symbol': '₮'},
    {'code': 'MOP', 'name': 'Macanese Pataca', 'numeric_code': 446, 'symbol': 'MOP$'},
    {'code': 'MRU', 'name': 'Mauritanian Ouguiya', 'numeric_code': 929, 'symbol': 'UM'},
    {'code': 'MUR', 'name': 'Mauritian Rupee', 'numeric_code': 480, 'symbol': '₨'},
    {'code': 'MVR', 'name': 'Maldivian Rufiyaa', 'numeric_code': 462, 'symbol': 'Rf'},
    {'code': 'MWK', 'name': 'Malawian Kwacha', 'numeric_code': 454, 'symbol': 'MK'},
    {'code': 'MXN', 'name': 'Mexican Peso', 'numeric_code': 484, 'symbol': '$'},
    {'code': 'MYR', 'name': 'Malaysian Ringgit', 'numeric_code': 458, 'symbol': 'RM'},
    {'code': 'MZN', 'name': 'Mozambican Metical', 'numeric_code': 943, 'symbol': 'MT'},
    {'code': 'NAD', 'name': 'Namibian Dollar', 'numeric_code': 516, 'symbol': '$'},
    {'code': 'NGN', 'name': 'Nigerian Naira', 'numeric_code': 566, 'symbol': '₦'},
    {'code': 'NIO', 'name': 'Nicaraguan Córdoba', 'numeric_code': 558, 'symbol': 'C$'},
    {'code': 'NOK', 'name': 'Norwegian Krone', 'numeric_code': 578, 'symbol': 'kr'},
    {'code': 'NPR', 'name': 'Nepalese Rupee', 'numeric_code': 524, 'symbol': '₨'},
    {'code': 'NZD', 'name': 'New Zealand Dollar', 'numeric_code': 554, 'symbol': '$'},
    {'code': 'OMR', 'name': 'Omani Rial', 'numeric_code': 512, 'symbol': '﷼'},
    {'code': 'PAB', 'name': 'Panamanian Balboa', 'numeric_code': 590, 'symbol': 'B/.'},
    {'code': 'PEN', 'name': 'Peruvian Sol', 'numeric_code': 604, 'symbol': 'S/.'},
    {'code': 'PGK', 'name': 'Papua New Guinean Kina', 'numeric_code': 598, 'symbol': 'K'},
    {'code': 'PHP', 'name': 'Philippine Peso', 'numeric_code': 608, 'symbol': '₱'},
    {'code': 'PKR', 'name': 'Pakistani Rupee', 'numeric_code': 586, 'symbol': '₨'},
    {'code': 'PLN', 'name': 'Polish Zloty', 'numeric_code': 985, 'symbol': 'zł'},
    {'code': 'PYG', 'name': 'Paraguayan Guarani', 'numeric_code': 600, 'symbol': 'Gs'},
    {'code': 'QAR', 'name': 'Qatari Riyal', 'numeric_code': 634, 'symbol': '﷼'},
    {'code': 'RON', 'name': 'Romanian Leu', 'numeric_code': 946, 'symbol': 'lei'},
    {'code': 'RSD', 'name': 'Serbian Dinar', 'numeric_code': 941, 'symbol': 'дин'},
    {'code': 'RUB', 'name': 'Russian Ruble', 'numeric_code': 643, 'symbol': '₽'},
    {'code': 'RWF', 'name': 'Rwandan Franc', 'numeric_code': 646, 'symbol': 'FRw'},
    {'code': 'SAR', 'name': 'Saudi Riyal', 'numeric_code': 682, 'symbol': '﷼'},
    {'code': 'SBD', 'name': 'Solomon Islands Dollar', 'numeric_code': 90, 'symbol': '$'},
    {'code': 'SCR', 'name': 'Seychellois Rupee', 'numeric_code': 690, 'symbol': '₨'},
    {'code': 'SDG', 'name': 'Sudanese Pound', 'numeric_code': 938, 'symbol': 'ج.س.'},
    {'code': 'SEK', 'name': 'Swedish Krona', 'numeric_code': 752, 'symbol': 'kr'},
    {'code': 'SGD', 'name': 'Singapore Dollar', 'numeric_code': 702, 'symbol': '$'},
    {'code': 'SHP', 'name': 'Saint Helena Pound', 'numeric_code': 654, 'symbol': '£'},
    {'code': 'SLL', 'name': 'Sierra Leonean Leone', 'numeric_code': 694, 'symbol': 'Le'},
    {'code': 'SOS', 'name': 'Somali Shilling', 'numeric_code': 706, 'symbol': 'S'},
    {'code': 'SRD', 'name': 'Surinamese Dollar', 'numeric_code': 968, 'symbol': '$'},
    {'code': 'SSP', 'name': 'South Sudanese Pound', 'numeric_code': 728, 'symbol': '£'},
    {'code': 'STN', 'name': 'São Tomé and Príncipe Dobra', 'numeric_code': 930, 'symbol': 'Db'},
    {'code': 'SVC', 'name': 'Salvadoran Colón', 'numeric_code': 222, 'symbol': '$'},
    {'code': 'SYP', 'name': 'Syrian Pound', 'numeric_code': 760, 'symbol': '£'},
    {'code': 'SZL', 'name': 'Swazi Lilangeni', 'numeric_code': 748, 'symbol': 'L'},
    {'code': 'THB', 'name': 'Thai Baht', 'numeric_code': 764, 'symbol': '฿'},
    {'code': 'TJS', 'name': 'Tajikistani Somoni', 'numeric_code': 972, 'symbol': 'SM'},
    {'code': 'TMT', 'name': 'Turkmenistani Manat', 'numeric_code': 934, 'symbol': 'T'},
    {'code': 'TND', 'name': 'Tunisian Dinar', 'numeric_code': 788, 'symbol': 'DT'},
    {'code': 'TOP', 'name': 'Tongan Paʻanga', 'numeric_code': 776, 'symbol': 'T$'},
    {'code': 'TRY', 'name': 'Turkish Lira', 'numeric_code': 949, 'symbol': '₺'},
    {'code': 'TTD', 'name': 'Trinidad and Tobago Dollar', 'numeric_code': 780, 'symbol': 'TT$'},
    {'code': 'TWD', 'name': 'New Taiwan Dollar', 'numeric_code': 901, 'symbol': 'NT$'},
    {'code': 'TZS', 'name': 'Tanzanian Shilling', 'numeric_code': 834, 'symbol': 'TSh'},
    {'code': 'UAH', 'name': 'Ukrainian Hryvnia', 'numeric_code': 980, 'symbol': '₴'},
    {'code': 'UGX', 'name': 'Ugandan Shilling', 'numeric_code': 800, 'symbol': 'USh'},
    {'code': 'USD', 'name': 'US Dollar', 'numeric_code': 840, 'symbol': '$'},
    {'code': 'UYU', 'name': 'Uruguayan Peso', 'numeric_code': 858, 'symbol': '$U'},
    {'code': 'UZS', 'name': 'Uzbekistani Som', 'numeric_code': 860, 'symbol': 'лв'},
    {'code': 'VES', 'name': 'Venezuelan Bolívar Soberano', 'numeric_code': 928, 'symbol': 'Bs.S'},
    {'code': 'VND', 'name': 'Vietnamese Đồng', 'numeric_code': 704, 'symbol': '₫'},
    {'code': 'VUV', 'name': 'Vanuatu Vatu', 'numeric_code': 548, 'symbol': 'VT'},
    {'code': 'WST', 'name': 'Samoan Tala', 'numeric_code': 882, 'symbol': 'WS$'},
    {'code': 'XAF', 'name': 'Central African CFA Franc', 'numeric_code': 950, 'symbol': 'FCFA'},
    {'code': 'XCD', 'name': 'East Caribbean Dollar', 'numeric_code': 951, 'symbol': '$'},
    {'code': 'XDR', 'name': 'Special Drawing Rights', 'numeric_code': 960, 'symbol': 'SDR'},
    {'code': 'XOF', 'name': 'West African CFA Franc', 'numeric_code': 952, 'symbol': 'CFA'},
    {'code': 'XPF', 'name': 'CFP Franc', 'numeric_code': 953, 'symbol': '₣'},
    {'code': 'YER', 'name': 'Yemeni Rial', 'numeric_code': 886, 'symbol': '﷼'},
    {'code': 'ZAR', 'name': 'South African Rand', 'numeric_code': 710, 'symbol': 'R'},
    {'code': 'ZMW', 'name': 'Zambian Kwacha', 'numeric_code': 967, 'symbol': 'ZK'},
    {'code': 'ZWL', 'name': 'Zimbabwean Dollar', 'numeric_code': 932, 'symbol': 'Z$'},
]

class Command(BaseCommand):
    help = 'Populates the Currency model with ISO 4217 data'

    def handle(self, *args, **options):
        created_count = 0
        for currency in CURRENCY_DATA:
            _, created = Currency.objects.get_or_create(
                code=currency['code'],
                defaults={
                    'name': currency['name'],
                    'numeric_code': currency['numeric_code'],
                    'symbol': currency.get('symbol', '')
                }
            )
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully populated currencies. Created {created_count} new entries.'))